CREATE TABLE SBI_PROGRESS_THREAD (
       PROGRESS_THREAD_ID   INTEGER NOT NULL,
       USER_ID              VARCHAR(100) NOT NULL,
       PARTIAL              INTEGER,
       TOTAL        	      INTEGER,
       FUNCTION_CD         VARCHAR(200),
       MESSAGE              VARCHAR(4000),
       RANDOM_KEY			VARCHAR(4000),	
       PRIMARY KEY (PROGRESS_THREAD_ID)
) WITHOUT OIDS;


INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(PROGRESS_THREAD_ID)+1 FROM SBI_PROGRESS_THREAD),1),'SBI_PROGRESS_THREAD');


ALTER TABLE SBI_EXT_ROLES ADD COLUMN DO_MASSIVE_EXPORT BOOLEAN DEFAULT TRUE;

ALTER TABLE SBI_UDP_VALUE ALTER COLUMN VALUE SET DEFAULT NULL;