/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.tools.objmetadata.metadata;
// Generated 18-nov-2009 17.58.49 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;


/**
 * SbiObjMetadata generated by hbm2java
 */

public class SbiObjMetadata  extends SbiHibernateModel {


    // Fields    

     private Integer objMetaId;
     private String label;
     private String name;
     private String description;
     private SbiDomains dataType;
     private Date creationDate;


    // Constructors

    /** default constructor */
    public SbiObjMetadata() {
    }

	/** minimal constructor */
    public SbiObjMetadata(Integer objMetaId, String label, String name, SbiDomains dataType, Date creationDate) {
        this.objMetaId = objMetaId;
        this.label = label;
        this.name = name;
        this.dataType = dataType;
        this.creationDate = creationDate;
    }
    
    /** full constructor */
    public SbiObjMetadata(Integer objMetaId, String label, String name, String description, SbiDomains dataType, Date creationDate) {
        this.objMetaId = objMetaId;
        this.label = label;
        this.name = name;
        this.description = description;
        this.dataType = dataType;
        this.creationDate = creationDate;
    }
    

   
    // Property accessors

    public Integer getObjMetaId() {
        return this.objMetaId;
    }
    
    public void setObjMetaId(Integer objMetaId) {
        this.objMetaId = objMetaId;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public SbiDomains getDataType() {
        return this.dataType;
    }
    
    public void setDataType(SbiDomains dataType) {
        this.dataType = dataType;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
   








}
