/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.behaviouralmodel.analyticaldriver.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;





/**
 * SbiParuseDet generated by hbm2java
 */
public class SbiParuseDet  extends SbiHibernateModel {

    // Fields    

     private SbiParuseDetId id;
     private Integer prog;
     
     private Short hiddenFl;
     private String defaultVal;


    // Constructors

    /**
     * default constructor.
     */
    public SbiParuseDet() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiParuseDet(SbiParuseDetId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiParuseDetId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiParuseDetId id) {
        this.id = id;
    }

    /**
     * Gets the prog.
     * 
     * @return the prog
     */
    public Integer getProg() {
        return this.prog;
    }
    
    /**
     * Sets the prog.
     * 
     * @param prog the new prog
     */
    public void setProg(Integer prog) {
        this.prog = prog;
    }



	/**
	 * Gets the default val.
	 * 
	 * @return the default val
	 */
	public String getDefaultVal() {
		return defaultVal;
	}
	
	/**
	 * Sets the default val.
	 * 
	 * @param defaultVal the new default val
	 */
	public void setDefaultVal(String defaultVal) {
		this.defaultVal = defaultVal;
	}
	
	/**
	 * Gets the hidden fl.
	 * 
	 * @return the hidden fl
	 */
	public Short getHiddenFl() {
		return hiddenFl;
	}
	
	/**
	 * Sets the hidden fl.
	 * 
	 * @param hiddenFl the new hidden fl
	 */
	public void setHiddenFl(Short hiddenFl) {
		this.hiddenFl = hiddenFl;
	}
}