/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.behaviouralmodel.analyticaldriver.metadata;

import it.eng.spagobi.commons.metadata.SbiExtRoles;




/**
 * SbiParuseDetId generated by hbm2java
 */
public class SbiParuseDetId  implements java.io.Serializable {

    // Fields    

     private SbiParuse sbiParuse;
     private SbiExtRoles sbiExtRoles;


    // Constructors

    /**
     * default constructor.
     */
    public SbiParuseDetId() {
    }
    
   
    
    

    // Property accessors

    /**
     * Gets the sbi paruse.
     * 
     * @return the sbi paruse
     */
    public SbiParuse getSbiParuse() {
        return this.sbiParuse;
    }
    
    /**
     * Sets the sbi paruse.
     * 
     * @param sbiParuse the new sbi paruse
     */
    public void setSbiParuse(SbiParuse sbiParuse) {
        this.sbiParuse = sbiParuse;
    }

    /**
     * Gets the sbi ext roles.
     * 
     * @return the sbi ext roles
     */
    public SbiExtRoles getSbiExtRoles() {
        return this.sbiExtRoles;
    }
    
    /**
     * Sets the sbi ext roles.
     * 
     * @param sbiExtRoles the new sbi ext roles
     */
    public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
        this.sbiExtRoles = sbiExtRoles;
    }

   /* (non-Javadoc)
    * @see java.lang.Object#equals(java.lang.Object)
    */
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiParuseDetId) ) return false;
		 SbiParuseDetId castOther = ( SbiParuseDetId ) other; 
         
		 return (this.getSbiParuse()==castOther.getSbiParuse()) || ( this.getSbiParuse()!=null && castOther.getSbiParuse()!=null && this.getSbiParuse().equals(castOther.getSbiParuse()) )
 && (this.getSbiExtRoles()==castOther.getSbiExtRoles()) || ( this.getSbiExtRoles()!=null && castOther.getSbiExtRoles()!=null && this.getSbiExtRoles().equals(castOther.getSbiExtRoles()) );
   }
   
   /* (non-Javadoc)
    * @see java.lang.Object#hashCode()
    */
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSbiParuse().hashCode();
         result = 37 * result + this.getSbiExtRoles().hashCode();
         return result;
   }   


}