package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.analiticalmodel.document.metadata.SbiObjects;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;



/**
 * SbiKpiRole generated by hbm2java
 */

public class SbiKpiDocument  extends SbiHibernateModel{

	// Fields    
	
    private Integer idKpiDoc;
    private SbiKpi sbiKpi;
    private SbiObjects sbiObjects;


   // Constructors

   /** default constructor */
   public SbiKpiDocument() {
	   this.idKpiDoc = -1;
   }

   
   /** full constructor */
   public SbiKpiDocument(Integer idKpiDoc, SbiKpi sbiKpi, SbiObjects sbiObjects) {
       this.idKpiDoc = idKpiDoc;
       this.sbiKpi = sbiKpi;
       this.sbiObjects = sbiObjects;
   }

  
   // Property accessors

   // Property accessors

   public Integer getIdKpiDoc() {
       return this.idKpiDoc;
   }
   
   public void setIdKpiDoc(Integer idKpiDoc) {
       this.idKpiDoc = idKpiDoc;
   }

   public SbiObjects getSbiObjects() {
       return this.sbiObjects;
   }
   
   public void setSbiObjects(SbiObjects sbiObjects) {
       this.sbiObjects = sbiObjects;
   }

   public SbiKpi getSbiKpi() {
       return this.sbiKpi;
   }
   
   public void setSbiKpi(SbiKpi sbiKpi) {
       this.sbiKpi = sbiKpi;
   }

}
