/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.analiticalmodel.document.metadata.SbiObjects;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;



/**
 * SbiKpiRole generated by hbm2java
 */

public class SbiKpiDocument  extends SbiHibernateModel{

	// Fields    
	
    private Integer idKpiDoc;
    private SbiKpi sbiKpi;
    private SbiObjects sbiObjects;


   // Constructors

   /** default constructor */
   public SbiKpiDocument() {
	   this.idKpiDoc = -1;
   }

   
   /** full constructor */
   public SbiKpiDocument(Integer idKpiDoc, SbiKpi sbiKpi, SbiObjects sbiObjects) {
       this.idKpiDoc = idKpiDoc;
       this.sbiKpi = sbiKpi;
       this.sbiObjects = sbiObjects;
   }

  
   // Property accessors

   // Property accessors

   public Integer getIdKpiDoc() {
       return this.idKpiDoc;
   }
   
   public void setIdKpiDoc(Integer idKpiDoc) {
       this.idKpiDoc = idKpiDoc;
   }

   public SbiObjects getSbiObjects() {
       return this.sbiObjects;
   }
   
   public void setSbiObjects(SbiObjects sbiObjects) {
       this.sbiObjects = sbiObjects;
   }

   public SbiKpi getSbiKpi() {
       return this.sbiKpi;
   }
   
   public void setSbiKpi(SbiKpi sbiKpi) {
       this.sbiKpi = sbiKpi;
   }

}
