/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;


// Generated 17-set-2010 11.25.47 by Hibernate Tools 3.2.4.GA

/**
 * SbiKpiRel generated by hbm2java
 */
public class SbiKpiRel extends SbiHibernateModel {

	private Integer kpiRelId;
	private SbiKpi sbiKpiByKpiChildId;
	private SbiKpi sbiKpiByKpiFatherId;
	private String parameter;

	public SbiKpiRel() {
	}

	public SbiKpiRel(SbiKpi sbiKpiByKpiChildId, SbiKpi sbiKpiByKpiFatherId) {
		this.sbiKpiByKpiChildId = sbiKpiByKpiChildId;
		this.sbiKpiByKpiFatherId = sbiKpiByKpiFatherId;
	}

	public SbiKpiRel(SbiKpi sbiKpiByKpiChildId, SbiKpi sbiKpiByKpiFatherId,
			String parameter) {
		this.sbiKpiByKpiChildId = sbiKpiByKpiChildId;
		this.sbiKpiByKpiFatherId = sbiKpiByKpiFatherId;
		this.parameter = parameter;
	}

	public Integer getKpiRelId() {
		return this.kpiRelId;
	}

	public void setKpiRelId(Integer kpiRelId) {
		this.kpiRelId = kpiRelId;
	}

	public SbiKpi getSbiKpiByKpiChildId() {
		return this.sbiKpiByKpiChildId;
	}

	public void setSbiKpiByKpiChildId(SbiKpi sbiKpiByKpiChildId) {
		this.sbiKpiByKpiChildId = sbiKpiByKpiChildId;
	}

	public SbiKpi getSbiKpiByKpiFatherId() {
		return this.sbiKpiByKpiFatherId;
	}

	public void setSbiKpiByKpiFatherId(SbiKpi sbiKpiByKpiFatherId) {
		this.sbiKpiByKpiFatherId = sbiKpiByKpiFatherId;
	}

	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

}
