/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.commons.metadata.SbiExtRoles;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;



/**
 * SbiKpiRole generated by hbm2java
 */

public class SbiKpiRole  extends SbiHibernateModel {


    // Fields    

     private Integer idKpiRole;
     private SbiExtRoles sbiExtRoles;
     private SbiKpi sbiKpi;


    // Constructors

    /** default constructor */
    public SbiKpiRole() {
    }

    
    /** full constructor */
    public SbiKpiRole(Integer idKpiRole, SbiExtRoles sbiExtRoles, SbiKpi sbiKpi) {
        this.idKpiRole = idKpiRole;
        this.sbiExtRoles = sbiExtRoles;
        this.sbiKpi = sbiKpi;
    }
    

   
    // Property accessors

    public Integer getIdKpiRole() {
        return this.idKpiRole;
    }
    
    public void setIdKpiRole(Integer idKpiRole) {
        this.idKpiRole = idKpiRole;
    }

    public SbiExtRoles getSbiExtRoles() {
        return this.sbiExtRoles;
    }
    
    public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
        this.sbiExtRoles = sbiExtRoles;
    }

    public SbiKpi getSbiKpi() {
        return this.sbiKpi;
    }
    
    public void setSbiKpi(SbiKpi sbiKpi) {
        this.sbiKpi = sbiKpi;
    }
   








}
