/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
// Generated 13-gen-2009 11.26.29 by Hibernate Tools 3.1.0 beta3



/**
 * SbiKpiInstPeriod generated by hbm2java
 */

public class SbiKpiInstPeriod  extends SbiHibernateModel {


    // Fields    

     private Integer kpiInstPeriodId;
     private SbiKpiInstance sbiKpiInstance;
     private SbiKpiPeriodicity sbiKpiPeriodicity;
     private Boolean default_;


    // Constructors

    /** default constructor */
    public SbiKpiInstPeriod() {
    }

    
    /** full constructor */
    public SbiKpiInstPeriod(Integer kpiInstPeriodId, SbiKpiInstance sbiKpiInstance, SbiKpiPeriodicity sbiKpiPeriodicity, Boolean default_) {
        this.kpiInstPeriodId = kpiInstPeriodId;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiKpiPeriodicity = sbiKpiPeriodicity;
        this.default_ = default_;
    }
    

   
    // Property accessors

    public Integer getKpiInstPeriodId() {
        return this.kpiInstPeriodId;
    }
    
    public void setKpiInstPeriodId(Integer kpiInstPeriodId) {
        this.kpiInstPeriodId = kpiInstPeriodId;
    }

    public SbiKpiInstance getSbiKpiInstance() {
        return this.sbiKpiInstance;
    }
    
    public void setSbiKpiInstance(SbiKpiInstance sbiKpiInstance) {
        this.sbiKpiInstance = sbiKpiInstance;
    }

    public SbiKpiPeriodicity getSbiKpiPeriodicity() {
        return this.sbiKpiPeriodicity;
    }
    
    public void setSbiKpiPeriodicity(SbiKpiPeriodicity sbiKpiPeriodicity) {
        this.sbiKpiPeriodicity = sbiKpiPeriodicity;
    }
   
    public Boolean isDefault_() {
        return this.default_;
    }
    
    public void setDefault_(Boolean default_) {
        this.default_ = default_;
    }







}
