package it.eng.spagobi.kpi.config.metadata;

import it.eng.spagobi.commons.metadata.SbiExtRoles;



/**
 * SbiKpiRole generated by hbm2java
 */

public class SbiKpiRole  implements java.io.Serializable {


    // Fields    

     private Integer idKpiRole;
     private SbiExtRoles sbiExtRoles;
     private SbiKpi sbiKpi;


    // Constructors

    /** default constructor */
    public SbiKpiRole() {
    }

    
    /** full constructor */
    public SbiKpiRole(Integer idKpiRole, SbiExtRoles sbiExtRoles, SbiKpi sbiKpi) {
        this.idKpiRole = idKpiRole;
        this.sbiExtRoles = sbiExtRoles;
        this.sbiKpi = sbiKpi;
    }
    

   
    // Property accessors

    public Integer getIdKpiRole() {
        return this.idKpiRole;
    }
    
    public void setIdKpiRole(Integer idKpiRole) {
        this.idKpiRole = idKpiRole;
    }

    public SbiExtRoles getSbiExtRoles() {
        return this.sbiExtRoles;
    }
    
    public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
        this.sbiExtRoles = sbiExtRoles;
    }

    public SbiKpi getSbiKpi() {
        return this.sbiKpi;
    }
    
    public void setSbiKpi(SbiKpi sbiKpi) {
        this.sbiKpi = sbiKpi;
    }
   








}
