package it.eng.spagobi.kpi.config.metadata;
// Generated 5-nov-2008 17.16.36 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.kpi.model.metadata.SbiResources;

import java.util.Date;


/**
 * SbiKpiValue generated by hbm2java
 */

public class SbiKpiValue  implements java.io.Serializable {


    // Fields    
	
     private Integer idKpiInstanceValue;
     private SbiKpiInstance sbiKpiInstance;
     private SbiResources sbiResources;
     private String value;
     private Date beginDt;
     private Date endDt;
     private String description;
     private String xmlData; 


    // Constructors

   

	/** default constructor */
    public SbiKpiValue() {
    }

	/** minimal constructor */
    public SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, SbiResources sbiResources) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiResources = sbiResources;
    }
    
    /** full constructor */
    public SbiKpiValue(Integer idKpiInstanceValue, SbiKpiInstance sbiKpiInstance, SbiResources sbiResources, String value, Date beginDt, Date endDt, String description, String xmlData) {
        this.idKpiInstanceValue = idKpiInstanceValue;
        this.sbiKpiInstance = sbiKpiInstance;
        this.sbiResources = sbiResources;
        this.value = value;
        this.beginDt = beginDt;
        this.endDt = endDt;
        this.description = description;
        this.xmlData = xmlData;
    }
    

   
    // Property accessors

    public Integer getIdKpiInstanceValue() {
        return this.idKpiInstanceValue;
    }
    
    public void setIdKpiInstanceValue(Integer idKpiInstanceValue) {
        this.idKpiInstanceValue = idKpiInstanceValue;
    }

    public SbiKpiInstance getSbiKpiInstance() {
        return this.sbiKpiInstance;
    }
    
    public void setSbiKpiInstance(SbiKpiInstance sbiKpiInstance) {
        this.sbiKpiInstance = sbiKpiInstance;
    }

    public SbiResources getSbiResources() {
        return this.sbiResources;
    }
    
    public void setSbiResources(SbiResources sbiResources) {
        this.sbiResources = sbiResources;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    public Date getBeginDt() {
        return this.beginDt;
    }
    
    public void setBeginDt(Date beginDt) {
        this.beginDt = beginDt;
    }

    public Date getEndDt() {
        return this.endDt;
    }
    
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }
   
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getXmlData() {
		return xmlData;
	}

	public void setXmlData(String xmlData) {
		this.xmlData = xmlData;
	}

}
