/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.tools.massiveExport.metadata;


/**s
 * SbiProgressThread generated by hbm2java
 */
public class SbiProgressThread implements java.io.Serializable {

	private int progressThreadId;
	private String userId;
	private Integer partial;
	private Integer total;
	private String functionCd;
	private String status;
	private String randomKey;
	private String type;

	public SbiProgressThread() {
	}

	public SbiProgressThread(int progressThreadId, String userId) {
		this.progressThreadId = progressThreadId;
		this.userId = userId;
	}

	public SbiProgressThread(int progressThreadId, String userId,
			Integer partial, Integer total, String functionCd, String status, String randomKey, String type) {
		this.progressThreadId = progressThreadId;
		this.userId = userId;
		this.partial = partial;
		this.total = total;
		this.functionCd = functionCd;
		this.status = status;
		this.randomKey = randomKey;
		this.type = type;
	}

	public int getProgressThreadId() {
		return this.progressThreadId;
	}

	public void setProgressThreadId(int progressThreadId) {
		this.progressThreadId = progressThreadId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getPartial() {
		return this.partial;
	}

	public void setPartial(Integer partial) {
		this.partial = partial;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public String getFunctionCd() {
		return this.functionCd;
	}

	public void setFunctionCd(String functionCd) {
		this.functionCd = functionCd;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRandomKey() {
		return randomKey;
	}

	public void setRandomKey(String randomKey) {
		this.randomKey = randomKey;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
