/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.analiticalmodel.document.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.Date;




/**
 * SbiObjState generated by hbm2java
 */
public class SbiObjState  extends SbiHibernateModel {

    // Fields    

     private SbiObjStateId id;
     private Date endDt;
     private String note;


    // Constructors

    /**
     * default constructor.
     */
    public SbiObjState() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiObjState(SbiObjStateId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiObjStateId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiObjStateId id) {
        this.id = id;
    }

    /**
     * Gets the end dt.
     * 
     * @return the end dt
     */
    public Date getEndDt() {
        return this.endDt;
    }
    
    /**
     * Sets the end dt.
     * 
     * @param endDt the new end dt
     */
    public void setEndDt(Date endDt) {
        this.endDt = endDt;
    }

    /**
     * Gets the note.
     * 
     * @return the note
     */
    public String getNote() {
        return this.note;
    }
    
    /**
     * Sets the note.
     * 
     * @param note the new note
     */
    public void setNote(String note) {
        this.note = note;
    }



}