function wpalo(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',Cb='<script defer="defer">wpalo.onInjectionDone(\'wpalo\')<\/script>',ac='<script id="',A='=',q='?',C='Bad handler "',Bb='DOMContentLoaded',tb="GWT module 'wpalo' needs to be (re)compiled, please run a compile or use the Compile/Browse button in hosted mode",o='SCRIPT',Fb='__gwt_marker_wpalo',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',Eb='end',mb='gecko',ob='gecko1_8',yb='gwt.hybrid',ub='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',Ab='head',rb='hosted.html?wpalo',zb='href',lb='ie6',kb='ie8',ab='iframe',t='img',bb="javascript:''",vb='link',qb='loadExternalRefs',v='meta',eb='moduleRequested',Db='moduleStartup',jb='msie',w='name',gb='opera',db='position:absolute;width:0;height:0;border:none',wb='rel',ib='safari',sb='selectingPermutation',x='startup',xb='stylesheet',pb='unknown',fb='user.agent',hb='webkit',m='wpalo';var cc=window,k=document,bc=cc.__gwtStatsEvent?function(a){return cc.__gwtStatsEvent(a)}:null,wc,mc,hc,gc=l,pc={},zc=[],vc=[],fc=[],sc,uc;bc&&bc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!cc.__gwt_stylesLoaded){cc.__gwt_stylesLoaded={}}if(!cc.__gwt_scriptsLoaded){cc.__gwt_scriptsLoaded={}}function lc(){var b=false;try{b=cc.external&&(cc.external.gwtOnLoad&&cc.location.search.indexOf(yb)==-1)}catch(a){}lc=function(){return b};return b}
function oc(){if(wc&&mc){var c=k.getElementById(m);var b=c.contentWindow;if(lc()){b.__gwt_getProperty=function(a){return ic(a)}}wpalo=null;b.gwtOnLoad(sc,m,gc);bc&&bc({moduleName:m,subSystem:x,evtGroup:Db,millis:(new Date()).getTime(),type:Eb})}}
function jc(){var j,h=Fb,i;k.write(ac+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){gc=f(j.src)}if(gc==l){var e=k.getElementsByTagName(s);if(e.length>0){gc=e[e.length-1].href}else{gc=f(k.location.href)}}else if(gc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=gc+u;gc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function tc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}pc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{uc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{sc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function ic(d){var e=vc[d](),b=zc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(uc){uc(d,a,e)}throw null}
var kc;function nc(){if(!kc){kc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);bc&&bc({moduleName:m,subSystem:x,evtGroup:Db,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(gc+xc)}}
vc[fb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(gb)!=-1){return gb}else if(d.indexOf(hb)!=-1){return ib}else if(d.indexOf(jb)!=-1){if(document.documentMode>=8){return kb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return lb}}}}else if(d.indexOf(mb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ob}return mb}return pb};zc[fb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};wpalo.onScriptLoad=function(){if(kc){mc=true;oc()}};wpalo.onInjectionDone=function(){wc=true;bc&&bc({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:Eb});oc()};jc();var xc;if(lc()){if(cc.external.initModule&&cc.external.initModule(m)){cc.location.reload();return}xc=rb}tc();bc&&bc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:sb});if(!xc){try{alert(tb);return}catch(a){return}}var rc;function qc(){if(!hc){hc=true;if(!__gwt_stylesLoaded[ub]){var a=k.createElement(vb);__gwt_stylesLoaded[ub]=a;a.setAttribute(wb,xb);a.setAttribute(zb,gc+ub);k.getElementsByTagName(Ab)[0].appendChild(a)}oc();if(k.removeEventListener){k.removeEventListener(Bb,qc,false)}if(rc){clearInterval(rc)}}}
if(k.addEventListener){k.addEventListener(Bb,function(){nc();qc()},false)}var rc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){nc();qc()}},50);bc&&bc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:Eb});bc&&bc({moduleName:m,subSystem:x,evtGroup:qb,millis:(new Date()).getTime(),type:nb});k.write(Cb)}
wpalo();