CREATE MEMORY TABLE SBI_COMMUNITY(COMMUNITY_ID INTEGER NOT NULL PRIMARY KEY, NAME varchar(200) NOT NULL, DESCRIPTION varchar(350) DEFAULT NULL, OWNER char(100) NOT NULL, FUNCT_CODE varchar(40) DEFAULT NULL, CREATION_DATE timestamp  DEFAULT NOW NOT NULL, LAST_CHANGE_DATE timestamp DEFAULT '0000-00-00 00:00:00'  NOT NULL, USER_IN varchar(100) NOT NULL, USER_UP varchar(100) DEFAULT NULL, USER_DE varchar(100) DEFAULT NULL, TIME_IN timestamp  DEFAULT '0000-00-00 00:00:00' NOT NULL, TIME_UP timestamp DEFAULT NULL, TIME_DE timestamp DEFAULT NULL, SBI_VERSION_IN varchar(10) DEFAULT NULL, SBI_VERSION_UP varchar(10) DEFAULT NULL, SBI_VERSION_DE varchar(10) DEFAULT NULL, META_VERSION varchar(100) DEFAULT NULL, ORGANIZATION varchar(20) DEFAULT NULL);
CREATE MEMORY TABLE SBI_COMMUNITY_USERS (COMMUNITY_ID INTEGER NOT NULL,USER_ID char(100) NOT NULL,CREATION_DATE timestamp DEFAULT NOW  NOT NULL,LAST_CHANGE_DATE timestamp  DEFAULT '0000-00-00 00:00:00' NOT NULL, USER_IN varchar(100) NOT NULL, USER_UP varchar(100) DEFAULT NULL, USER_DE varchar(100) DEFAULT NULL, TIME_IN timestamp  DEFAULT '0000-00-00 00:00:00' NOT NULL, TIME_UP timestamp DEFAULT NULL, TIME_DE timestamp DEFAULT NULL, SBI_VERSION_IN varchar(10) DEFAULT NULL, SBI_VERSION_UP varchar(10) DEFAULT NULL, SBI_VERSION_DE varchar(10) DEFAULT NULL, META_VERSION varchar(100) DEFAULT NULL, ORGANIZATION varchar(20) DEFAULT NULL, PRIMARY KEY (COMMUNITY_ID,USER_ID), CONSTRAINT FK_COMMUNITY FOREIGN KEY (COMMUNITY_ID) REFERENCES SBI_COMMUNITY (COMMUNITY_ID));

ALTER TABLE SBI_OBJECTS ADD COLUMN PREVIEW_FILE VARCHAR(100);

INSERT INTO SBI_USER_FUNC (USER_FUNCT_ID, NAME, DESCRIPTION, USER_IN, TIME_IN)
    VALUES ((SELECT next_val FROM hibernate_sequences WHERE sequence_name = 'SBI_USER_FUNC'), 
    'MeasuresCatalogueManagement','MeasuresCatalogueManagement', 'server', current_timestamp);
update hibernate_sequences set next_val = next_val+1 where sequence_name = 'SBI_USER_FUNC';

INSERT INTO SBI_ROLE_TYPE_USER_FUNC (ROLE_TYPE_ID, USER_FUNCT_ID)
    VALUES ((SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'ADMIN' AND DOMAIN_CD = 'ROLE_TYPE'), 
    (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME = 'MeasuresCatalogueManagement'));
commit;

INSERT INTO SBI_ROLE_TYPE_USER_FUNC (ROLE_TYPE_ID, USER_FUNCT_ID)
    VALUES ((SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'ADMIN' AND DOMAIN_CD = 'ROLE_TYPE'), 
    (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME = 'CreateWorksheetFromDatasetUserFunctionality'));
INSERT INTO SBI_ROLE_TYPE_USER_FUNC (ROLE_TYPE_ID, USER_FUNCT_ID)
    VALUES ((SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'DEV_ROLE' AND DOMAIN_CD = 'ROLE_TYPE'), 
    (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME = 'CreateWorksheetFromDatasetUserFunctionality'));
INSERT INTO SBI_ROLE_TYPE_USER_FUNC (ROLE_TYPE_ID, USER_FUNCT_ID)
    VALUES ((SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'TEST_ROLE' AND DOMAIN_CD = 'ROLE_TYPE'), 
    (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME = 'CreateWorksheetFromDatasetUserFunctionality'));
INSERT INTO SBI_ROLE_TYPE_USER_FUNC (ROLE_TYPE_ID, USER_FUNCT_ID)
    VALUES ((SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'MODEL_ADMIN' AND DOMAIN_CD = 'ROLE_TYPE'), 
    (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME = 'CreateWorksheetFromDatasetUserFunctionality'));
commit;

CREATE MEMORY TABLE SBI_GEO_LAYERS (LAYER_ID INTEGER NOT NULL, LABEL varchar(100) NOT NULL, NAME varchar(100), DESCR varchar(100), LAYER_DEFINITION LONGVARBINARY NOT NULL, TYPE varchar(40), USER_IN varchar(100) NOT NULL, USER_UP varchar(100) DEFAULT NULL, USER_DE varchar(100) DEFAULT NULL, TIME_IN timestamp  DEFAULT '0000-00-00 00:00:00' NOT NULL, TIME_UP timestamp DEFAULT NULL, TIME_DE timestamp DEFAULT NULL, SBI_VERSION_IN varchar(10) DEFAULT NULL, SBI_VERSION_UP varchar(10) DEFAULT NULL,  SBI_VERSION_DE varchar(10) DEFAULT NULL, META_VERSION varchar(100) DEFAULT NULL, ORGANIZATION varchar(20) DEFAULT NULL, CONSTRAINT LABEL_UNIQUE UNIQUE (ORGANIZATION, LABEL ASC), PRIMARY KEY (LAYER_ID)) ;


INSERT into SBI_DOMAINS (VALUE_ID, VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS, USER_IN) 
values ((SELECT next_val FROM hibernate_sequences WHERE sequence_name = 'SBI_DOMAINS'),'file','File','LAYER_TYPE','Layer Type','Layer Type','');
UPDATE hibernate_sequences SET next_val = (SELECT MAX(VALUE_ID) + 1 FROM SBI_DOMAINS) WHERE sequence_name = 'SBI_DOMAINS';  

INSERT into SBI_DOMAINS (VALUE_ID, VALUE_CD,VALUE_NM,DOMAIN_CD,DOMAIN_NM,VALUE_DS, USER_IN) 
values ((SELECT next_val FROM hibernate_sequences WHERE sequence_name = 'SBI_DOMAINS'),'wfs','Wfs','LAYER_TYPE','Layer Type','Layer Type','');
UPDATE hibernate_sequences SET next_val = (SELECT MAX(VALUE_ID) + 1 FROM SBI_DOMAINS) WHERE sequence_name = 'SBI_DOMAINS';  

INSERT INTO SBI_USER_FUNC (USER_FUNCT_ID, NAME, DESCRIPTION, USER_IN, TIME_IN)
    VALUES ((SELECT next_val FROM hibernate_sequences WHERE sequence_name = 'SBI_USER_FUNC'), 
    'GeoLayersManagement','GeoLayersManagement', 'server', current_timestamp);
update hibernate_sequences set next_val = next_val+1 where sequence_name = 'SBI_USER_FUNC';

INSERT INTO SBI_ROLE_TYPE_USER_FUNC (ROLE_TYPE_ID, USER_FUNCT_ID)
    VALUES ((SELECT VALUE_ID FROM SBI_DOMAINS WHERE VALUE_CD = 'ADMIN' AND DOMAIN_CD = 'ROLE_TYPE'), 
    (SELECT USER_FUNCT_ID FROM SBI_USER_FUNC WHERE NAME = 'GeoLayersManagement'));
commit;


ALTER TABLE SBI_COMMUNITY ADD UNIQUE INDEX NAME_UNIQUE (ORGANIZATION, NAME ASC) ; 