package it.eng.spagobi.kpi.model.metadata;
// Generated 5-nov-2008 17.17.20 by Hibernate Tools 3.1.0 beta3



/**
 * SbiKpiModelAttrVal generated by hbm2java
 */

public class SbiKpiModelAttrVal  implements java.io.Serializable {


    // Fields    

     private Integer kpiModelAttrValId;
     private SbiKpiModelAttr sbiKpiModelAttr;
     private SbiKpiModel sbiKpiModel;
     private String value;


    // Constructors

    /** default constructor */
    public SbiKpiModelAttrVal() {
    this.kpiModelAttrValId = -1;
    }

	/** minimal constructor */
    public SbiKpiModelAttrVal(Integer kpiModelAttrValId, SbiKpiModelAttr sbiKpiModelAttr, SbiKpiModel sbiKpiModel) {
        this.kpiModelAttrValId = kpiModelAttrValId;
        this.sbiKpiModelAttr = sbiKpiModelAttr;
        this.sbiKpiModel = sbiKpiModel;
    }
    
    /** full constructor */
    public SbiKpiModelAttrVal(Integer kpiModelAttrValId, SbiKpiModelAttr sbiKpiModelAttr, SbiKpiModel sbiKpiModel, String value) {
        this.kpiModelAttrValId = kpiModelAttrValId;
        this.sbiKpiModelAttr = sbiKpiModelAttr;
        this.sbiKpiModel = sbiKpiModel;
        this.value = value;
    }
    

   
    // Property accessors

    public Integer getKpiModelAttrValId() {
        return this.kpiModelAttrValId;
    }
    
    public void setKpiModelAttrValId(Integer kpiModelAttrValId) {
        this.kpiModelAttrValId = kpiModelAttrValId;
    }

    public SbiKpiModelAttr getSbiKpiModelAttr() {
        return this.sbiKpiModelAttr;
    }
    
    public void setSbiKpiModelAttr(SbiKpiModelAttr sbiKpiModelAttr) {
        this.sbiKpiModelAttr = sbiKpiModelAttr;
    }

    public SbiKpiModel getSbiKpiModel() {
        return this.sbiKpiModel;
    }
    
    public void setSbiKpiModel(SbiKpiModel sbiKpiModel) {
        this.sbiKpiModel = sbiKpiModel;
    }

    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
   








}
