package it.eng.spagobi.kpi.model.metadata;
// Generated 5-nov-2008 17.17.20 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiDomains;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiKpiModelAttr generated by hbm2java
 */

public class SbiKpiModelAttr  implements java.io.Serializable {


    // Fields    

     private Integer kpiModelAttrId;
     private SbiDomains sbiDomains;
     private String kpiModelAttrCd;
     private String kpiModelAttrNm;
     private String kpiModelAttrDescr;
     private Set sbiKpiModelAttrVals = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiKpiModelAttr() {
    this.kpiModelAttrId = -1;
    }

	/** minimal constructor */
    public SbiKpiModelAttr(Integer kpiModelAttrId, SbiDomains sbiDomains) {
        this.kpiModelAttrId = kpiModelAttrId;
        this.sbiDomains = sbiDomains;
    }
    
    /** full constructor */
    public SbiKpiModelAttr(Integer kpiModelAttrId, SbiDomains sbiDomains, String kpiModelAttrCd, String kpiModelAttrNm, String kpiModelAttrDescr, Set sbiKpiModelAttrVals) {
        this.kpiModelAttrId = kpiModelAttrId;
        this.sbiDomains = sbiDomains;
        this.kpiModelAttrCd = kpiModelAttrCd;
        this.kpiModelAttrNm = kpiModelAttrNm;
        this.kpiModelAttrDescr = kpiModelAttrDescr;
        this.sbiKpiModelAttrVals = sbiKpiModelAttrVals;
    }
    

   
    // Property accessors

    public Integer getKpiModelAttrId() {
        return this.kpiModelAttrId;
    }
    
    public void setKpiModelAttrId(Integer kpiModelAttrId) {
        this.kpiModelAttrId = kpiModelAttrId;
    }

    public SbiDomains getSbiDomains() {
        return this.sbiDomains;
    }
    
    public void setSbiDomains(SbiDomains sbiDomains) {
        this.sbiDomains = sbiDomains;
    }

    public String getKpiModelAttrCd() {
        return this.kpiModelAttrCd;
    }
    
    public void setKpiModelAttrCd(String kpiModelAttrCd) {
        this.kpiModelAttrCd = kpiModelAttrCd;
    }

    public String getKpiModelAttrNm() {
        return this.kpiModelAttrNm;
    }
    
    public void setKpiModelAttrNm(String kpiModelAttrNm) {
        this.kpiModelAttrNm = kpiModelAttrNm;
    }

    public String getKpiModelAttrDescr() {
        return this.kpiModelAttrDescr;
    }
    
    public void setKpiModelAttrDescr(String kpiModelAttrDescr) {
        this.kpiModelAttrDescr = kpiModelAttrDescr;
    }

    public Set getSbiKpiModelAttrVals() {
        return this.sbiKpiModelAttrVals;
    }
    
    public void setSbiKpiModelAttrVals(Set sbiKpiModelAttrVals) {
        this.sbiKpiModelAttrVals = sbiKpiModelAttrVals;
    }
   








}
