/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;

/**
 * SbiAttribute generated by hbm2java
 */
public class SbiAttribute extends SbiHibernateModel {

	private int attributeId;
	private String attributeName;
	private String description;
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(
			0);

	public SbiAttribute() {
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
	}

	public SbiAttribute(int attributeId, String attributeName,
			String description, Set<SbiUserAttributes> sbiUserAttributeses) {
		this.attributeId = attributeId;
		this.attributeName = attributeName;
		this.description = description;
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

}
