/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005-2009 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/
package it.eng.spagobi.profiling.bean;

// Generated 22-dic-2009 14.20.04 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SbiUser generated by hbm2java
 */
public class SbiUser implements java.io.Serializable {

	private int id;
	private String userId;
	private String password;
	private String fullName;
	private Date dtPwdBegin;
	private Date dtPwdEnd;
	private Boolean flgPwdBlocked;
	private Date dtLastAccess;
	
	private Set<SbiExtUserRoles> sbiExtUserRoleses = new HashSet<SbiExtUserRoles>(
			0);
	private Set<SbiUserAttributes> sbiUserAttributeses = new HashSet<SbiUserAttributes>(
			0);

	public SbiUser() {
	}

	public SbiUser(int id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public SbiUser(int id, String userId, String password, String fullName,
			Date dtPwdBegin, Date dtPwdEnd, Boolean flgPwdBlocked,
			Date dtLastAccess,
			Set<SbiExtUserRoles> sbiExtUserRoleses,
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.id = id;
		this.userId = userId;
		this.password = password;
		this.fullName = fullName;
		this.dtPwdBegin = dtPwdBegin;
		this.dtPwdEnd = dtPwdEnd;
		this.flgPwdBlocked = flgPwdBlocked;
		this.dtLastAccess = dtLastAccess;
		this.sbiExtUserRoleses = sbiExtUserRoleses;
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public Date getDtPwdBegin() {
		return this.dtPwdBegin;
	}

	public void setDtPwdBegin(Date dtPwdBegin) {
		this.dtPwdBegin = dtPwdBegin;
	}

	public Date getDtPwdEnd() {
		return this.dtPwdEnd;
	}

	public void setDtPwdEnd(Date dtPwdEnd) {
		this.dtPwdEnd = dtPwdEnd;
	}

	public Boolean getFlgPwdBlocked() {
		return this.flgPwdBlocked;
	}

	public void setFlgPwdBlocked(Boolean flgPwdBlocked) {
		this.flgPwdBlocked = flgPwdBlocked;
	}

	public Date getDtLastAccess() {
		return this.dtLastAccess;
	}

	public void setDtLastAccess(Date dtLastAccess) {
		this.dtLastAccess = dtLastAccess;
	}
	
	public Set<SbiExtUserRoles> getSbiExtUserRoleses() {
		return this.sbiExtUserRoleses;
	}

	public void setSbiExtUserRoleses(Set<SbiExtUserRoles> sbiExtUserRoleses) {
		this.sbiExtUserRoleses = sbiExtUserRoleses;
	}

	public Set<SbiUserAttributes> getSbiUserAttributeses() {
		return this.sbiUserAttributeses;
	}

	public void setSbiUserAttributeses(
			Set<SbiUserAttributes> sbiUserAttributeses) {
		this.sbiUserAttributeses = sbiUserAttributeses;
	}

}
