package it.eng.spagobi.commons.metadata;

import it.eng.spagobi.commons.bo.Config;



/**
 * SbiConfig generated by hbm2java
 */

public class SbiConfig  extends SbiHibernateModel {


    // Fields    

     private Integer id;
     private SbiDomains sbiDomains;
     private String label;
     private String name;
     private String description;
     private boolean isActive;
     private String valueCheck;


    // Constructors

    /** default constructor */
    public SbiConfig() {
    }

	/** minimal constructor */
    public SbiConfig(Integer id, String label) {
        this.id = id;
        this.label = label;
    }
    
    /** full constructor */
    public SbiConfig(Integer id, SbiDomains sbiDomains, String label, String name, String description, boolean isActive, String valueCheck) {
        this.id = id;
        this.sbiDomains = sbiDomains;
        this.label = label;
        this.name = name;
        this.description = description;
        this.isActive = isActive;
        this.valueCheck = valueCheck;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public SbiDomains getSbiDomains() {
        return this.sbiDomains;
    }
    
    public void setSbiDomains(SbiDomains sbiDomains) {
        this.sbiDomains = sbiDomains;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    public String getValueCheck() {
        return this.valueCheck;
    }
    
    public void setValueCheck(String valueCheck) {
        this.valueCheck = valueCheck;
    }

    /**
	 * From the Hibernate SbiConfig object at input, gives the corrispondent
	 * <code>Config</code> object.
	 * 
	 * @param hibConf The Hibernate Config object
	 * 
	 * @return the corrispondent output <code>Config</code>
	 */
	public Config toConfig(){

		Config config = new Config();
		config.setId(getId());
		config.setLabel(getLabel());
		config.setName(getName());
		config.setDescription(getDescription());
		config.setActive(isActive);
		config.setValueCheck(getValueCheck());
		SbiDomains tmpDom = getSbiDomains();
		if (tmpDom != null) { 
			config.setValueTypeId(tmpDom.getValueId().intValue());
		}
		return config;
	}



}
