package it.eng.spagobi.commons.metadata;

// Generated 2-dic-2013 14.44.44 by Hibernate Tools 3.4.0.CR1

/**
 * SbiFunctionalitiesRolesId generated by hbm2java
 */
public class SbiFunctionalitiesRolesId implements java.io.Serializable {

	private int functionalityId;
	private int roleId;

	public SbiFunctionalitiesRolesId() {
	}

	public SbiFunctionalitiesRolesId(int functionalityId, int roleId) {
		this.functionalityId = functionalityId;
		this.roleId = roleId;
	}

	public int getFunctionalityId() {
		return this.functionalityId;
	}

	public void setFunctionalityId(int functionalityId) {
		this.functionalityId = functionalityId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SbiFunctionalitiesRolesId))
			return false;
		SbiFunctionalitiesRolesId castOther = (SbiFunctionalitiesRolesId) other;

		return (this.getFunctionalityId() == castOther.getFunctionalityId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFunctionalityId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
