package it.eng.spagobi.commons.metadata;

// Generated 2-dic-2013 14.44.44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SbiFunctionalitiesRoles generated by hbm2java
 */
public class SbiFunctionalitiesRoles extends SbiHibernateModel {

	private SbiFunctionalitiesRolesId id;
	private SbiExtRoles sbiExtRoles;
	private SbiFunctionalities sbiFunctionalities;
	private String userIn;
	private String userUp;
	private String userDe;
	private Date timeIn;
	private Date timeUp;
	private Date timeDe;
	private String sbiVersionIn;
	private String sbiVersionUp;
	private String sbiVersionDe;
	private String metaVersion;
	private String organization;

	public SbiFunctionalitiesRoles() {
	}

	public SbiFunctionalitiesRoles(SbiFunctionalitiesRolesId id,
			SbiExtRoles sbiExtRoles, SbiFunctionalities sbiFunctionalities,
			String userIn, Date timeIn) {
		this.id = id;
		this.sbiExtRoles = sbiExtRoles;
		this.sbiFunctionalities = sbiFunctionalities;
		this.userIn = userIn;
		this.timeIn = timeIn;
	}

	public SbiFunctionalitiesRoles(SbiFunctionalitiesRolesId id,
			SbiExtRoles sbiExtRoles, SbiFunctionalities sbiFunctionalities,
			String userIn, String userUp, String userDe, Date timeIn,
			Date timeUp, Date timeDe, String sbiVersionIn, String sbiVersionUp,
			String sbiVersionDe, String metaVersion, String organization) {
		this.id = id;
		this.sbiExtRoles = sbiExtRoles;
		this.sbiFunctionalities = sbiFunctionalities;
		this.userIn = userIn;
		this.userUp = userUp;
		this.userDe = userDe;
		this.timeIn = timeIn;
		this.timeUp = timeUp;
		this.timeDe = timeDe;
		this.sbiVersionIn = sbiVersionIn;
		this.sbiVersionUp = sbiVersionUp;
		this.sbiVersionDe = sbiVersionDe;
		this.metaVersion = metaVersion;
		this.organization = organization;
	}

	public SbiFunctionalitiesRolesId getId() {
		return this.id;
	}

	public void setId(SbiFunctionalitiesRolesId id) {
		this.id = id;
	}

	public SbiExtRoles getSbiExtRoles() {
		return this.sbiExtRoles;
	}

	public void setSbiExtRoles(SbiExtRoles sbiExtRoles) {
		this.sbiExtRoles = sbiExtRoles;
	}

	public SbiFunctionalities getSbiFunctionalities() {
		return this.sbiFunctionalities;
	}

	public void setSbiFunctionalities(SbiFunctionalities sbiFunctionalities) {
		this.sbiFunctionalities = sbiFunctionalities;
	}

	public String getUserIn() {
		return this.userIn;
	}

	public void setUserIn(String userIn) {
		this.userIn = userIn;
	}

	public String getUserUp() {
		return this.userUp;
	}

	public void setUserUp(String userUp) {
		this.userUp = userUp;
	}

	public String getUserDe() {
		return this.userDe;
	}

	public void setUserDe(String userDe) {
		this.userDe = userDe;
	}

	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	public Date getTimeUp() {
		return this.timeUp;
	}

	public void setTimeUp(Date timeUp) {
		this.timeUp = timeUp;
	}

	public Date getTimeDe() {
		return this.timeDe;
	}

	public void setTimeDe(Date timeDe) {
		this.timeDe = timeDe;
	}

	public String getSbiVersionIn() {
		return this.sbiVersionIn;
	}

	public void setSbiVersionIn(String sbiVersionIn) {
		this.sbiVersionIn = sbiVersionIn;
	}

	public String getSbiVersionUp() {
		return this.sbiVersionUp;
	}

	public void setSbiVersionUp(String sbiVersionUp) {
		this.sbiVersionUp = sbiVersionUp;
	}

	public String getSbiVersionDe() {
		return this.sbiVersionDe;
	}

	public void setSbiVersionDe(String sbiVersionDe) {
		this.sbiVersionDe = sbiVersionDe;
	}

	public String getMetaVersion() {
		return this.metaVersion;
	}

	public void setMetaVersion(String metaVersion) {
		this.metaVersion = metaVersion;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

}
