/**

SpagoBI - The Business Intelligence Free Platform

Copyright (C) 2005-2008 Engineering Ingegneria Informatica S.p.A.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

**/


package it.eng.spagobi.engines.config.metadata;




// Generated 4-giu-2009 12.50.24 by Hibernate Tools 3.1.0 beta3



/**
 * SbiExportersId generated by hbm2java
 */

public class SbiExportersId  implements java.io.Serializable {


    // Fields    

     private Integer engineId;
     private Integer domainId;


    // Constructors

    /** default constructor */
    public SbiExportersId() {
    }

    
    /** full constructor */
    public SbiExportersId(Integer engineId, Integer domainId) {
        this.engineId = engineId;
        this.domainId = domainId;
    }
    

   
    // Property accessors

    public Integer getEngineId() {
        return this.engineId;
    }
    
    public void setEngineId(Integer engineId) {
        this.engineId = engineId;
    }

    public Integer getDomainId() {
        return this.domainId;
    }
    
    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbiExportersId) ) return false;
		 SbiExportersId castOther = ( SbiExportersId ) other; 
         
		 return ( (this.getEngineId()==castOther.getEngineId()) || ( this.getEngineId()!=null && castOther.getEngineId()!=null && this.getEngineId().equals(castOther.getEngineId()) ) )
 && ( (this.getDomainId()==castOther.getDomainId()) || ( this.getDomainId()!=null && castOther.getDomainId()!=null && this.getDomainId().equals(castOther.getDomainId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEngineId() == null ? 0 : this.getEngineId().hashCode() );
         result = 37 * result + ( getDomainId() == null ? 0 : this.getDomainId().hashCode() );
         return result;
   }   





}
