DROP TABLE TWITTER_SENTIMENT CASCADE;

DROP TABLE TWITTER_SEARCH_SCHEDULER CASCADE;

DROP TABLE TWITTER_MONITOR_SCHEDULER CASCADE;

DROP TABLE TWITTER_LINK_TO_MONITOR_CAT CASCADE;

DROP TABLE TWITTER_LINKS_TO_MONITOR CASCADE;

DROP TABLE TWITTER_ACCOUNTS_TO_MONITOR CASCADE;

DROP TABLE TWITTER_DATA CASCADE;

DROP TABLE TWITTER_USERS CASCADE;

DROP TABLE TWITTER_SEARCH CASCADE;

DROP TABLE TWITTER_HIBERNATE_SEQUENCES CASCADE;