/*SQLSERVER doesn't support the  option, so is necessary to drop before all constraints and then the table!!*/

ALTER TABLE SBI_DIST_LIST_USER DROP CONSTRAINT AK1SBI_DIST_LIST_USER;
ALTER TABLE SBI_DIST_LIST_USER DROP CONSTRAINT AK1SBI_DL_USER;
ALTER TABLE SBI_DIST_LIST_USER DROP CONSTRAINT FK_SBI_DIST_LIST_USER_1;
DROP TABLE SBI_DIST_LIST_USER  ;

ALTER TABLE SBI_DIST_LIST_OBJECTS DROP CONSTRAINT AK1SBI_DIST_LIST_OBJECTS;
ALTER TABLE SBI_DIST_LIST_OBJECTS DROP CONSTRAINT FK_SBI_DIST_LIST_OBJECTS_1;
ALTER TABLE SBI_DIST_LIST_OBJECTS DROP CONSTRAINT FK_SBI_DIST_LIST_OBJECTS_2;
DROP TABLE SBI_DIST_LIST_OBJECTS ;

ALTER TABLE SBI_DIST_LIST DROP CONSTRAINT AK1SBI_SBI_DIST_LIST;
DROP TABLE SBI_DIST_LIST  ;

ALTER TABLE SBI_DOSSIER_PRES DROP CONSTRAINT AK1SBI_DOSSIER_PRES;
ALTER TABLE SBI_DOSSIER_PRES DROP CONSTRAINT FK_SBI_DOSSIER_PRES_1;
ALTER TABLE SBI_DOSSIER_PRES DROP CONSTRAINT FK_SBI_DOSSIER_PRES_2;
DROP TABLE SBI_DOSSIER_PRES  ;

ALTER TABLE SBI_DOSSIER_BIN_TEMP DROP CONSTRAINT AK1SBI_DOSSIER_BIN_TEMP;
ALTER TABLE SBI_DOSSIER_BIN_TEMP DROP CONSTRAINT FK_SBI_DOSSIER_BIN_TEMP_1;
DROP TABLE SBI_DOSSIER_BIN_TEMP  ;

ALTER TABLE SBI_DOSSIER_TEMP DROP CONSTRAINT AK1SBI_DOSSIER_TEMP;
ALTER TABLE SBI_DOSSIER_TEMP DROP CONSTRAINT FK_SBI_DOSSIER_TEMP_1;
DROP TABLE SBI_DOSSIER_TEMP  ;
 
ALTER TABLE SBI_REMEMBER_ME DROP CONSTRAINT AK1SBI_REMEMBER_ME;
ALTER TABLE SBI_REMEMBER_ME DROP CONSTRAINT FK_SBI_REMEMBER_ME_1;
ALTER TABLE SBI_REMEMBER_ME DROP CONSTRAINT FK_SBI_REMEMBER_ME_2;
DROP TABLE SBI_REMEMBER_ME ;

ALTER TABLE SBI_AUDIT DROP CONSTRAINT FK_SBI_AUDIT_1;
ALTER TABLE SBI_AUDIT DROP CONSTRAINT FK_SBI_AUDIT_2;
ALTER TABLE SBI_AUDIT DROP CONSTRAINT FK_SBI_AUDIT_3;
DROP TABLE SBI_AUDIT  ;

ALTER TABLE SBI_EVENTS_ROLES DROP CONSTRAINT FK_SBI_EVENTS_ROLES_1;
ALTER TABLE SBI_EVENTS_ROLES DROP CONSTRAINT FK_SBI_EVENTS_ROLES_2;
DROP TABLE SBI_EVENTS_ROLES  ;

DROP TABLE SBI_EVENTS_LOG  ;
DROP TABLE SBI_EVENTS  ;

ALTER TABLE SBI_MENU_ROLE DROP CONSTRAINT FK_SBI_MENU_ROLE1;
ALTER TABLE SBI_MENU_ROLE DROP CONSTRAINT FK_SBI_MENU_ROLE2;
DROP TABLE SBI_MENU_ROLE  ;

DROP TABLE SBI_MENU  ;

ALTER TABLE SBI_ALARM_DISTRIBUTION DROP CONSTRAINT FK_SBI_ALARM_DISTRIBUTION_1;
ALTER TABLE SBI_ALARM_DISTRIBUTION DROP CONSTRAINT FK_SBI_ALARM_DISTRIBUTION_2;
DROP TABLE SBI_ALARM_DISTRIBUTION  ;

ALTER TABLE SBI_ALARM_CONTACT DROP CONSTRAINT XIF1SBI_ALARM_CONTACT;
DROP TABLE SBI_ALARM_CONTACT  ;

ALTER TABLE SBI_ALARM_EVENT DROP CONSTRAINT FK_SBI_ALARM_EVENT_1;
DROP TABLE SBI_ALARM_EVENT  ;

ALTER TABLE SBI_ALARM DROP CONSTRAINT FK_SBI_ALARM_1;
ALTER TABLE SBI_ALARM DROP CONSTRAINT FK_SBI_ALARM_2;
ALTER TABLE SBI_ALARM DROP CONSTRAINT FK_SBI_ALARM_3;
ALTER TABLE SBI_ALARM DROP CONSTRAINT FK_SBI_ALARM_4;
ALTER TABLE SBI_ALARM DROP CONSTRAINT XIF1SBI_ALARM;
DROP TABLE SBI_ALARM  ;

ALTER TABLE SBI_KPI_MODEL_RESOURCES DROP CONSTRAINT FK_SBI_KPI_MODEL_RESOURCES_1;
ALTER TABLE SBI_KPI_MODEL_RESOURCES DROP CONSTRAINT FK_SBI_KPI_MODEL_RESOURCES_2;
DROP TABLE SBI_KPI_MODEL_RESOURCES  ;

ALTER TABLE SBI_KPI_ERROR DROP CONSTRAINT FK_SBI_KPI_ERROR_MODEL_1;
DROP TABLE SBI_KPI_ERROR ;

ALTER TABLE SBI_ORG_UNIT_GRANT_NODES DROP CONSTRAINT FK_SBI_ORG_UNIT_GRANT_NODES_1;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES DROP CONSTRAINT FK_SBI_ORG_UNIT_GRANT_NODES_2;
ALTER TABLE SBI_ORG_UNIT_GRANT_NODES DROP CONSTRAINT FK_SBI_ORG_UNIT_GRANT_NODES_3;
DROP TABLE SBI_ORG_UNIT_GRANT_NODES ;

ALTER TABLE SBI_ORG_UNIT_NODES DROP CONSTRAINT FK_SBI_ORG_UNIT_NODES_1;
ALTER TABLE SBI_ORG_UNIT_NODES DROP CONSTRAINT FK_SBI_ORG_UNIT_NODES_2;
ALTER TABLE SBI_ORG_UNIT_NODES DROP CONSTRAINT FK_SBI_ORG_UNIT_NODES_3;
DROP TABLE SBI_ORG_UNIT_NODES ;

ALTER TABLE SBI_GOAL_KPI DROP CONSTRAINT FK_SBI_GOAL_KPI_GOAL;
ALTER TABLE SBI_GOAL_KPI DROP CONSTRAINT FK_SBI_GOAL_KPI_KPI;
DROP TABLE SBI_GOAL_KPI  ;

ALTER TABLE SBI_GOAL_HIERARCHY DROP CONSTRAINT FK_SBI_GOAL_HIERARCHY_GOAL;
ALTER TABLE SBI_GOAL_HIERARCHY DROP CONSTRAINT FK_SBI_GOAL_HIERARCHY_PARENT;
DROP TABLE SBI_GOAL_HIERARCHY  ;

ALTER TABLE SBI_GOAL DROP CONSTRAINT FK_GRANT_ID_GRANT;
DROP TABLE SBI_GOAL  ;

ALTER TABLE SBI_ORG_UNIT_GRANT DROP CONSTRAINT FK_SBI_ORG_UNIT_GRANT_2;
ALTER TABLE SBI_ORG_UNIT_GRANT DROP CONSTRAINT FK_SBI_ORG_UNIT_GRANT_3;
ALTER TABLE SBI_ORG_UNIT_GRANT DROP CONSTRAINT XIF1SBI_ORG_UNIT_GRANT;
DROP TABLE SBI_ORG_UNIT_GRANT ;

ALTER TABLE SBI_KPI_MODEL_INST DROP CONSTRAINT FK_SBI_KPI_MODEL_INST_1;
ALTER TABLE SBI_KPI_MODEL_INST DROP CONSTRAINT FK_SBI_KPI_MODEL_INST_2;
ALTER TABLE SBI_KPI_MODEL_INST DROP CONSTRAINT FK_SBI_KPI_MODEL_INST_3;
ALTER TABLE SBI_KPI_MODEL_INST DROP CONSTRAINT XAK2SBI_KPI_MODEL_INST;
DROP TABLE SBI_KPI_MODEL_INST  ;

ALTER TABLE SBI_KPI_INST_PERIOD DROP CONSTRAINT FK_SBI_KPI_INST_PERIOD_1;
ALTER TABLE SBI_KPI_INST_PERIOD DROP CONSTRAINT FK_SBI_KPI_INST_PERIOD_2;
DROP TABLE SBI_KPI_INST_PERIOD  ;

ALTER TABLE SBI_KPI_INSTANCE_HISTORY DROP CONSTRAINT FK_SBI_KPI_INSTANCE_HISTORY_1;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY DROP CONSTRAINT FK_SBI_KPI_INSTANCE_HISTORY_2;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY DROP CONSTRAINT FK_SBI_KPI_INSTANCE_HISTORY_3;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY DROP CONSTRAINT FK_SBI_KPI_INSTANCE_HISTORY_4;
ALTER TABLE SBI_KPI_INSTANCE_HISTORY DROP CONSTRAINT XIF1SBI_KPI_INST_HISTORY;
DROP TABLE SBI_KPI_INSTANCE_HISTORY  ;

ALTER TABLE SBI_KPI_PERIODICITY DROP CONSTRAINT XIF1SBI_KPI_PERIODICITY;
DROP TABLE SBI_KPI_PERIODICITY  ;

ALTER TABLE SBI_KPI_VALUE DROP CONSTRAINT FK_SBI_KPI_VALUE_1;
ALTER TABLE SBI_KPI_VALUE DROP CONSTRAINT FK_SBI_KPI_VALUE_2;
ALTER TABLE SBI_KPI_VALUE DROP CONSTRAINT FK_SBI_KPI_VALUE_4;
ALTER TABLE SBI_KPI_VALUE DROP CONSTRAINT XIF1SBI_KPI_VALUE;
DROP TABLE SBI_KPI_VALUE  ;

ALTER TABLE SBI_KPI_MODEL DROP CONSTRAINT FK_SBI_KPI_MODEL_1;
ALTER TABLE SBI_KPI_MODEL DROP CONSTRAINT FK_SBI_KPI_MODEL_2;
ALTER TABLE SBI_KPI_MODEL DROP CONSTRAINT FK_SBI_KPI_MODEL_3;
ALTER TABLE SBI_KPI_MODEL DROP CONSTRAINT UNIQUE_PAR_ID_CD;
ALTER TABLE SBI_KPI_MODEL DROP CONSTRAINT XIF1SBI_KPI_MODEL;
DROP TABLE SBI_KPI_MODEL  ;

ALTER TABLE SBI_KPI_INSTANCE DROP CONSTRAINT FK_SBI_KPI_INSTANCE_1;
ALTER TABLE SBI_KPI_INSTANCE DROP CONSTRAINT FK_SBI_KPI_INSTANCE_2;
ALTER TABLE SBI_KPI_INSTANCE DROP CONSTRAINT FK_SBI_KPI_INSTANCE_3;
ALTER TABLE SBI_KPI_INSTANCE DROP CONSTRAINT FK_SBI_KPI_INSTANCE_4;
DROP TABLE SBI_KPI_INSTANCE  ;

ALTER TABLE SBI_KPI_DOCUMENTS DROP CONSTRAINT FK_SBI_KPI_DOCUMENTS_1;
ALTER TABLE SBI_KPI_DOCUMENTS DROP CONSTRAINT FK_SBI_KPI_DOCUMENTS_2;
DROP TABLE SBI_KPI_DOCUMENTS ;

ALTER TABLE SBI_KPI_ROLE DROP CONSTRAINT AK1SBI_KPI_ROLE;
ALTER TABLE SBI_KPI_ROLE DROP CONSTRAINT FK_SBI_KPI_ROLE_1;
ALTER TABLE SBI_KPI_ROLE DROP CONSTRAINT FK_SBI_KPI_ROLE_2;
DROP TABLE SBI_KPI_ROLE  ;

ALTER TABLE SBI_KPI_REL DROP CONSTRAINT FK_SBI_KPI_REL_3;
ALTER TABLE SBI_KPI_REL DROP CONSTRAINT FK_SBI_KPI_REL_4;
DROP TABLE SBI_KPI_REL  ;

ALTER TABLE SBI_KPI DROP CONSTRAINT AK1SBI_KPI;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_1;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_2;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_3;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_4;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_5;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_6;
ALTER TABLE SBI_KPI DROP CONSTRAINT FK_SBI_KPI_7;
DROP TABLE SBI_KPI  ;

ALTER TABLE SBI_MEASURE_UNIT DROP CONSTRAINT FK_SBI_MEASURE_UNIT_1;
DROP TABLE SBI_MEASURE_UNIT  ;

ALTER TABLE SBI_THRESHOLD_VALUE DROP CONSTRAINT FK_SBI_THRESHOLD_VALUE_1;
ALTER TABLE SBI_THRESHOLD_VALUE DROP CONSTRAINT FK_SBI_THRESHOLD_VALUE_2;
ALTER TABLE SBI_THRESHOLD_VALUE DROP CONSTRAINT XIF1SBI_THRESHOLD_VALUE;
DROP TABLE SBI_THRESHOLD_VALUE  ;

ALTER TABLE SBI_THRESHOLD DROP CONSTRAINT FK_SBI_THRESHOLD_1;
ALTER TABLE SBI_THRESHOLD DROP CONSTRAINT XIF1SBI_THRESHOLD;
DROP TABLE SBI_THRESHOLD  ;

ALTER TABLE SBI_RESOURCES DROP CONSTRAINT FK_SBI_RESOURCES_1;
ALTER TABLE SBI_RESOURCES DROP CONSTRAINT XIF1SBI_RESOURCES;
DROP TABLE SBI_RESOURCES  ;

DROP TABLE SBI_ACTIVITY_MONITORING ;

ALTER TABLE SBI_OBJ_METACONTENTS DROP CONSTRAINT FK_SBI_OBJ_METACONTENTS_1;
ALTER TABLE SBI_OBJ_METACONTENTS DROP CONSTRAINT FK_SBI_OBJ_METACONTENTS_2;
ALTER TABLE SBI_OBJ_METACONTENTS DROP CONSTRAINT FK_SBI_OBJ_METACONTENTS_3;
ALTER TABLE SBI_OBJ_METACONTENTS DROP CONSTRAINT FK_SBI_OBJ_METACONTENTS_4;
ALTER TABLE SBI_OBJ_METACONTENTS DROP CONSTRAINT XAK1SBI_OBJ_METACONTENTS;
DROP TABLE SBI_OBJ_METACONTENTS  ;

ALTER TABLE SBI_OBJ_METADATA DROP CONSTRAINT FK_SBI_OBJ_METADATA_1;
ALTER TABLE SBI_OBJ_METADATA DROP CONSTRAINT XAK1SBI_OBJ_METADATA;
DROP TABLE SBI_OBJ_METADATA  ;

ALTER TABLE SBI_SNAPSHOTS DROP CONSTRAINT AK1SBI_SNAPSHOTS;
ALTER TABLE SBI_SNAPSHOTS DROP CONSTRAINT FK_SBI_SNAPSHOTS_1;
ALTER TABLE SBI_SNAPSHOTS DROP CONSTRAINT FK_SBI_SNAPSHOTS_2;
DROP TABLE SBI_SNAPSHOTS  ;

ALTER TABLE SBI_SUBOBJECTS DROP CONSTRAINT AK1SBI_SUBOBJECTS;
ALTER TABLE SBI_SUBOBJECTS DROP CONSTRAINT FK_SBI_SUBOBJECTS_1;
ALTER TABLE SBI_SUBOBJECTS DROP CONSTRAINT FK_SBI_SUBOBJECTS_2;
DROP TABLE SBI_SUBOBJECTS  ;

ALTER TABLE SBI_OBJ_STATE DROP CONSTRAINT FK_SBI_OBJ_STATE_1;
ALTER TABLE SBI_OBJ_STATE DROP CONSTRAINT FK_SBI_OBJ_STATE_2;
DROP TABLE SBI_OBJ_STATE  ;

ALTER TABLE SBI_OBJECTS_RATING DROP CONSTRAINT FK_SBI_OBJECTS_RATING_1;
DROP TABLE SBI_OBJECTS_RATING ;

ALTER TABLE SBI_ROLE_TYPE_USER_FUNC DROP CONSTRAINT AK1SBI_ROLE_TYPE_USER_FUNC;
ALTER TABLE SBI_ROLE_TYPE_USER_FUNC DROP CONSTRAINT FK_SBI_ROLE_TYPE_USER_FUNC_1;
ALTER TABLE SBI_ROLE_TYPE_USER_FUNC DROP CONSTRAINT FK_SBI_ROLE_TYPE_USER_FUNC_2;
DROP TABLE SBI_ROLE_TYPE_USER_FUNC  ;

ALTER TABLE SBI_USER_FUNC DROP CONSTRAINT AK1SBI_USER_FUNC;
DROP TABLE SBI_USER_FUNC  ;

ALTER TABLE SBI_USER_ATTRIBUTES DROP CONSTRAINT FK_SBI_USER_ATTRIBUTES_1;
ALTER TABLE SBI_USER_ATTRIBUTES DROP CONSTRAINT FK_SBI_USER_ATTRIBUTES_2;
DROP TABLE SBI_USER_ATTRIBUTES  ;

DROP TABLE SBI_ATTRIBUTE ;

ALTER TABLE SBI_OBJ_PARUSE DROP CONSTRAINT FK_SBI_OBJ_PARUSE_1;
ALTER TABLE SBI_OBJ_PARUSE DROP CONSTRAINT FK_SBI_OBJ_PARUSE_2;
ALTER TABLE SBI_OBJ_PARUSE DROP CONSTRAINT FK_SBI_OBJ_PARUSE_3;
DROP TABLE SBI_OBJ_PARUSE  ;

ALTER TABLE SBI_PARUSE_CK DROP CONSTRAINT FK_SBI_PARUSE_CK_1;
ALTER TABLE SBI_PARUSE_CK DROP CONSTRAINT FK_SBI_PARUSE_CK_2;
DROP TABLE SBI_PARUSE_CK  ;

ALTER TABLE SBI_PARUSE_DET DROP CONSTRAINT FK_SBI_PARUSE_DET_1;
ALTER TABLE SBI_PARUSE_DET DROP CONSTRAINT FK_SBI_PARUSE_DET_2;
DROP TABLE SBI_PARUSE_DET  ;

ALTER TABLE SBI_PARUSE DROP CONSTRAINT FK_SBI_PARUSE_1;
ALTER TABLE SBI_PARUSE DROP CONSTRAINT FK_SBI_PARUSE_2;
ALTER TABLE SBI_PARUSE DROP CONSTRAINT XAK1SBI_PARUSE;
DROP TABLE SBI_PARUSE  ;

ALTER TABLE SBI_FUNC_ROLE DROP CONSTRAINT FK_SBI_FUNC_ROLE_1;
ALTER TABLE SBI_FUNC_ROLE DROP CONSTRAINT FK_SBI_FUNC_ROLE_2;
ALTER TABLE SBI_FUNC_ROLE DROP CONSTRAINT FK_SBI_FUNC_ROLE_3;
DROP TABLE SBI_FUNC_ROLE  ;

ALTER TABLE SBI_OBJ_FUNC DROP CONSTRAINT FK_SBI_OBJ_FUNC_1;
ALTER TABLE SBI_OBJ_FUNC DROP CONSTRAINT FK_SBI_OBJ_FUNC_2;
DROP TABLE SBI_OBJ_FUNC  ;

ALTER TABLE SBI_FUNCTIONS DROP CONSTRAINT FK_SBI_FUNCTIONS_1;
ALTER TABLE SBI_FUNCTIONS DROP CONSTRAINT FK_SBI_FUNCTIONS_2;
ALTER TABLE SBI_FUNCTIONS DROP CONSTRAINT XAK1SBI_FUNCTIONS;
DROP TABLE SBI_FUNCTIONS  ;

ALTER TABLE SBI_CHECKS DROP CONSTRAINT FK_SBI_CHECKS_1;
ALTER TABLE SBI_CHECKS DROP CONSTRAINT XAK1SBI_CHECKS;
DROP TABLE SBI_CHECKS  ;

ALTER TABLE SBI_OBJ_PARVIEW DROP CONSTRAINT FK_SBI_OBJ_PARVIEW_1;
ALTER TABLE SBI_OBJ_PARVIEW DROP CONSTRAINT FK_SBI_OBJ_PARVIEW_2;
drop table SBI_OBJ_PARVIEW ;

ALTER TABLE SBI_OBJ_PAR DROP CONSTRAINT FK_SBI_OBJ_PAR_1;
ALTER TABLE SBI_OBJ_PAR DROP CONSTRAINT FK_SBI_OBJ_PAR_2;
DROP TABLE SBI_OBJ_PAR  ;

ALTER TABLE SBI_PARAMETERS DROP CONSTRAINT FK_SBI_PARAMETERS_1;
ALTER TABLE SBI_PARAMETERS DROP CONSTRAINT XAK1SBI_PARAMETERS;
DROP TABLE SBI_PARAMETERS  ;

ALTER TABLE SBI_GEO_MAP_FEATURES DROP CONSTRAINT FK_GEO_MAP_FEATURES1;
ALTER TABLE SBI_GEO_MAP_FEATURES DROP CONSTRAINT FK_GEO_MAP_FEATURES2;
DROP TABLE SBI_GEO_MAP_FEATURES  ;

ALTER TABLE SBI_GEO_FEATURES DROP CONSTRAINT XAK1SBI_GEO_FEATURES;
DROP TABLE SBI_GEO_FEATURES  ;

ALTER TABLE SBI_GEO_MAPS DROP CONSTRAINT FK_SBI_GEO_MAPS_1;
ALTER TABLE SBI_GEO_MAPS DROP CONSTRAINT XAK1SBI_GEO_MAPS;
DROP TABLE SBI_GEO_MAPS  ;

ALTER TABLE SBI_VIEWPOINTS DROP CONSTRAINT FK_SBI_VIEWPOINTS_1;
DROP TABLE SBI_VIEWPOINTS  ;

ALTER TABLE SBI_SUBREPORTS DROP CONSTRAINT FK_SBI_SUBREPORTS_1;
ALTER TABLE SBI_SUBREPORTS DROP CONSTRAINT FK_SBI_SUBREPORTS_2;
DROP TABLE SBI_SUBREPORTS  ;

ALTER TABLE SBI_OBJECT_NOTES DROP CONSTRAINT AK1SBI_OBJECT_NOTES;
ALTER TABLE SBI_OBJECT_NOTES DROP CONSTRAINT FK_SBI_OBJECT_NOTES_1;
ALTER TABLE SBI_OBJECT_NOTES DROP CONSTRAINT FK_SBI_OBJECT_NOTES_2;
DROP TABLE SBI_OBJECT_NOTES  ;

ALTER TABLE SBI_OBJECT_TEMPLATES DROP CONSTRAINT AK1SBI_OBJECT_TEMPLATES;
ALTER TABLE SBI_OBJECT_TEMPLATES DROP CONSTRAINT FK_SBI_OBJECT_TEMPLATES_1;
ALTER TABLE SBI_OBJECT_TEMPLATES DROP CONSTRAINT FK_SBI_OBJECT_TEMPLATES_2;
DROP TABLE SBI_OBJECT_TEMPLATES  ;

ALTER TABLE SBI_BINARY_CONTENTS DROP CONSTRAINT AK1SBI_BINARY_CONTENTS;
DROP TABLE SBI_BINARY_CONTENTS  ;

ALTER TABLE SBI_LOV DROP CONSTRAINT FK_SBI_LOV_1;
ALTER TABLE SBI_LOV DROP CONSTRAINT XAK1SBI_LOV;
DROP TABLE SBI_LOV  ;

ALTER TABLE SBI_EXPORTERS DROP CONSTRAINT FK_SBI_EXPORTERS_1;
ALTER TABLE SBI_EXPORTERS DROP CONSTRAINT FK_SBI_EXPORTERS_2;
ALTER TABLE SBI_EXPORTERS DROP CONSTRAINT XAK1SBI_EXPORTERS;
DROP TABLE SBI_EXPORTERS ;

ALTER TABLE SBI_EXT_USER_ROLES DROP CONSTRAINT FK_SBI_EXT_USER_ROLES_1;
ALTER TABLE SBI_EXT_USER_ROLES DROP CONSTRAINT FK_SBI_EXT_USER_ROLES_2;
DROP TABLE SBI_EXT_USER_ROLES ;

ALTER TABLE SBI_EXT_ROLES DROP CONSTRAINT FK_SBI_EXT_ROLES_1;
ALTER TABLE SBI_EXT_ROLES DROP CONSTRAINT XAK1SBI_EXT_ROLES;
DROP TABLE SBI_EXT_ROLES  ;

ALTER TABLE SBI_USER DROP CONSTRAINT XAK1SBI_USER;
DROP TABLE SBI_USER  ;

ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_1;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_2;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_3;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_4;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_5;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_6;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT FK_SBI_OBJECTS_7;
ALTER TABLE SBI_OBJECTS DROP CONSTRAINT XAK1SBI_OBJECTS;
DROP TABLE SBI_OBJECTS  ;

ALTER TABLE SBI_ENGINES DROP CONSTRAINT FK_SBI_ENGINE_3;
ALTER TABLE SBI_ENGINES DROP CONSTRAINT FK_SBI_ENGINES_1;
ALTER TABLE SBI_ENGINES DROP CONSTRAINT FK_SBI_ENGINES_2;
ALTER TABLE SBI_ENGINES DROP CONSTRAINT XAK1SBI_ENGINES;
DROP TABLE SBI_ENGINES  ;

ALTER TABLE SBI_CONFIG DROP CONSTRAINT FK_SBI_CONFIG_1;
ALTER TABLE SBI_CONFIG DROP CONSTRAINT XAK1SBI_CONFIG;
DROP TABLE SBI_CONFIG  ;

ALTER TABLE SBI_UDP_VALUE DROP CONSTRAINT FK_SBI_UDP_VALUE_2;
DROP TABLE SBI_UDP_VALUE  ;

ALTER TABLE SBI_UDP DROP CONSTRAINT FK_SBI_SBI_UDP_1;
ALTER TABLE SBI_UDP DROP CONSTRAINT FK_SBI_SBI_UDP_2;
ALTER TABLE SBI_UDP DROP CONSTRAINT XAK1SBI_UDP;
DROP TABLE SBI_UDP  ;

ALTER TABLE SBI_ORG_UNIT_HIERARCHIES DROP CONSTRAINT XIF1SBI_ORG_UNIT_HIERARCHIES;
DROP TABLE SBI_ORG_UNIT_HIERARCHIES ;

ALTER TABLE SBI_ORG_UNIT DROP CONSTRAINT XIF1SBI_ORG_UNIT;
DROP TABLE SBI_ORG_UNIT ;

ALTER TABLE SBI_DATA_SET_HISTORY DROP CONSTRAINT FK_SBI_DATA_SET_CAT;
ALTER TABLE SBI_DATA_SET_HISTORY DROP CONSTRAINT FK_SBI_DATA_SET_DS;
ALTER TABLE SBI_DATA_SET_HISTORY DROP CONSTRAINT FK_SBI_DATA_SET_DS2;
ALTER TABLE SBI_DATA_SET_HISTORY DROP CONSTRAINT FK_SBI_DATA_SET_T;
DROP TABLE SBI_DATA_SET_HISTORY ;

ALTER TABLE SBI_DATA_SET DROP CONSTRAINT AK1SBI_DATA_SET;
DROP TABLE SBI_DATA_SET ;

ALTER TABLE SBI_DATA_SOURCE DROP CONSTRAINT AK1SBI_DATA_SOURCE;
ALTER TABLE SBI_DATA_SOURCE DROP CONSTRAINT FK_SBI_DATA_SOURCE_1;
DROP TABLE SBI_DATA_SOURCE  ;

ALTER TABLE SBI_DOMAINS DROP CONSTRAINT XAK1SBI_DOMAINS;
DROP TABLE SBI_DOMAINS  ;

DROP TABLE HIBERNATE_SEQUENCES ;