CREATE TABLE SBI_PROGRESS_THREAD (
       PROGRESS_THREAD_ID   INTEGER NOT NULL,
       USER_ID              VARCHAR2(100) NOT NULL,
       PARTIAL              INTEGER,
       TOTAL        	      INTEGER,
       FUNCTION_CD         VARCHAR2(200),
       MESSAGE              VARCHAR2(4000),
       RANDOM_KEY			VARCHAR2(4000),	
       PRIMARY KEY (PROGRESS_THREAD_ID)
);

INSERT INTO hibernate_sequences(NEXT_VAL,SEQUENCE_NAME) VALUES (COALESCE((SELECT MAX(PROGRESS_THREAD_ID)+1 FROM SBI_PROGRESS_THREAD),1),'SBI_PROGRESS_THREAD');

ALTER TABLE SBI_EXT_ROLES ADD COLUMN DO_MASSIVE_EXPORT NUMBER(38,0) DEFAULT 1;

ALTER TABLE SBI_UDP_VALUE  MODIFY (VALUE NULL);