package it.eng.spagobi.community.mapping;

// Generated 11-lug-2013 17.41.46 by Hibernate Tools 3.4.0.CR1

import it.eng.spagobi.commons.metadata.SbiHibernateModel;
import it.eng.spagobi.profiling.bean.SbiUser;

import java.util.Date;

/**
 * SbiCommunityUsers generated by hbm2java
 */
public class SbiCommunityUsers  extends SbiHibernateModel implements java.io.Serializable {

	private SbiCommunityUsersId id;
	private SbiUser sbiUser;
	private SbiCommunity sbiCommunity;
	private Date creationDate;
	private Date lastChangeDate;
	private String userIn;
	private String userUp;
	private String userDe;
	private Date timeIn;
	private Date timeUp;
	private Date timeDe;
	private String sbiVersionIn;
	private String sbiVersionUp;
	private String sbiVersionDe;
	private String metaVersion;
	private String organization;

	public SbiCommunityUsers() {
	}

	public SbiCommunityUsers(SbiCommunityUsersId id, SbiUser sbiUser,
			SbiCommunity sbiCommunity, Date creationDate, Date lastChangeDate,
			String userIn, Date timeIn) {
		this.id = id;
		this.sbiUser = sbiUser;
		this.sbiCommunity = sbiCommunity;
		this.creationDate = creationDate;
		this.lastChangeDate = lastChangeDate;
		this.userIn = userIn;
		this.timeIn = timeIn;
	}

	public SbiCommunityUsers(SbiCommunityUsersId id, SbiUser sbiUser,
			SbiCommunity sbiCommunity, Date creationDate, Date lastChangeDate,
			String userIn, String userUp, String userDe, Date timeIn,
			Date timeUp, Date timeDe, String sbiVersionIn, String sbiVersionUp,
			String sbiVersionDe, String metaVersion, String organization) {
		this.id = id;
		this.sbiUser = sbiUser;
		this.sbiCommunity = sbiCommunity;
		this.creationDate = creationDate;
		this.lastChangeDate = lastChangeDate;
		this.userIn = userIn;
		this.userUp = userUp;
		this.userDe = userDe;
		this.timeIn = timeIn;
		this.timeUp = timeUp;
		this.timeDe = timeDe;
		this.sbiVersionIn = sbiVersionIn;
		this.sbiVersionUp = sbiVersionUp;
		this.sbiVersionDe = sbiVersionDe;
		this.metaVersion = metaVersion;
		this.organization = organization;
	}

	public SbiCommunityUsersId getId() {
		return this.id;
	}

	public void setId(SbiCommunityUsersId id) {
		this.id = id;
	}

	public SbiUser getSbiUser() {
		return this.sbiUser;
	}

	public void setSbiUser(SbiUser sbiUser) {
		this.sbiUser = sbiUser;
	}

	public SbiCommunity getSbiCommunity() {
		return this.sbiCommunity;
	}

	public void setSbiCommunity(SbiCommunity sbiCommunity) {
		this.sbiCommunity = sbiCommunity;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastChangeDate() {
		return this.lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	public String getUserIn() {
		return this.userIn;
	}

	public void setUserIn(String userIn) {
		this.userIn = userIn;
	}

	public String getUserUp() {
		return this.userUp;
	}

	public void setUserUp(String userUp) {
		this.userUp = userUp;
	}

	public String getUserDe() {
		return this.userDe;
	}

	public void setUserDe(String userDe) {
		this.userDe = userDe;
	}

	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	public Date getTimeUp() {
		return this.timeUp;
	}

	public void setTimeUp(Date timeUp) {
		this.timeUp = timeUp;
	}

	public Date getTimeDe() {
		return this.timeDe;
	}

	public void setTimeDe(Date timeDe) {
		this.timeDe = timeDe;
	}

	public String getSbiVersionIn() {
		return this.sbiVersionIn;
	}

	public void setSbiVersionIn(String sbiVersionIn) {
		this.sbiVersionIn = sbiVersionIn;
	}

	public String getSbiVersionUp() {
		return this.sbiVersionUp;
	}

	public void setSbiVersionUp(String sbiVersionUp) {
		this.sbiVersionUp = sbiVersionUp;
	}

	public String getSbiVersionDe() {
		return this.sbiVersionDe;
	}

	public void setSbiVersionDe(String sbiVersionDe) {
		this.sbiVersionDe = sbiVersionDe;
	}

	public String getMetaVersion() {
		return this.metaVersion;
	}

	public void setMetaVersion(String metaVersion) {
		this.metaVersion = metaVersion;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

}
