/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.kpi.threshold.metadata;
// Generated 5-nov-2008 17.17.42 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiThreshold generated by hbm2java
 */

public class SbiThreshold  extends SbiHibernateModel {


    // Fields    

     private Integer thresholdId;
     private SbiDomains thresholdType;   
     private String name;
     private String description;
     private String code;
     private Set sbiKpis = new HashSet(0);
     private Set sbiKpiInstanceHistories = new HashSet(0);
     private Set sbiKpiInstances = new HashSet(0);
     private Set sbiThresholdValues = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiThreshold() {
    }
    
	/** minimal constructor */
    public SbiThreshold(Integer thresholdId, SbiDomains sbiDomains) {
        this.thresholdId = thresholdId;
        this.thresholdType = sbiDomains;
    }
    
    /** full constructor */
    public SbiThreshold(Integer thresholdId, SbiDomains sbiDomains, String name, String description, String code, Set sbiKpis, Set sbiKpiInstanceHistories, Set sbiKpiInstances, Set sbiThresholdValues) {
        this.thresholdId = thresholdId;
        this.thresholdType = sbiDomains;
        this.name = name;
        this.description = description;
        this.code = code;
        this.sbiKpis = sbiKpis;
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
        this.sbiKpiInstances = sbiKpiInstances;
        this.sbiThresholdValues = sbiThresholdValues;
    }
    

   
    // Property accessors

    public Integer getThresholdId() {
        return this.thresholdId;
    }
    
    public void setThresholdId(Integer thresholdId) {
        this.thresholdId = thresholdId;
    }


    public SbiDomains getThresholdType() {
		return thresholdType;
	}

	public void setThresholdType(SbiDomains thresholdTypeId) {
		this.thresholdType = thresholdTypeId;
	}

	public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getCode() {
    	return this.code;
    }
    
    public void setCode(String code) {
    	this.code = code;
    }
    public Set getSbiKpis() {
        return this.sbiKpis;
    }
    
    public void setSbiKpis(Set sbiKpis) {
        this.sbiKpis = sbiKpis;
    }

    public Set getSbiKpiInstanceHistories() {
        return this.sbiKpiInstanceHistories;
    }
    
    public void setSbiKpiInstanceHistories(Set sbiKpiInstanceHistories) {
        this.sbiKpiInstanceHistories = sbiKpiInstanceHistories;
    }

    public Set getSbiKpiInstances() {
        return this.sbiKpiInstances;
    }
    
    public void setSbiKpiInstances(Set sbiKpiInstances) {
        this.sbiKpiInstances = sbiKpiInstances;
    }

    public Set getSbiThresholdValues() {
        return this.sbiThresholdValues;
    }
    
    public void setSbiThresholdValues(Set sbiThresholdValues) {
        this.sbiThresholdValues = sbiThresholdValues;
    }
   
}
