package it.eng.spagobi.kpi.threshold.metadata;

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;



/**
 * SbiThresholdValue generated by hbm2java
 */

public class SbiThresholdValue  extends SbiHibernateModel {


    // Fields    

     private Integer idThresholdValue;
     private SbiThreshold sbiThreshold;
     private SbiDomains severity;
     private Double minValue;
     private Double maxValue;
     private String label;
     private String colour;
     private Integer position;
     private Set sbiAlarms = new HashSet(0);
     
     private Boolean minClosed;
     private Boolean maxClosed;
     private Double thValue;


    // Constructors

    /** default constructor */
    public SbiThresholdValue() {
    }

	/** minimal constructor */
    public SbiThresholdValue(Integer idThresholdValue, SbiThreshold sbiThreshold) {
        this.idThresholdValue = idThresholdValue;
        this.sbiThreshold = sbiThreshold;
    }
    
    /** full constructor */
    public SbiThresholdValue(Integer idThresholdValue, SbiThreshold sbiThreshold, SbiDomains sbiDomains, double minValue, double maxValue, String label, String colour, Integer position, Set sbiAlarms) {
        this.idThresholdValue = idThresholdValue;
        this.sbiThreshold = sbiThreshold;
        this.severity = sbiDomains;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.label = label;
        this.colour = colour;
        this.position = position;
        this.sbiAlarms = sbiAlarms;
    }
    

   
    // Property accessors

    public Integer getIdThresholdValue() {
        return this.idThresholdValue;
    }
    
    public void setIdThresholdValue(Integer idThresholdValue) {
        this.idThresholdValue = idThresholdValue;
    }

    public SbiThreshold getSbiThreshold() {
        return this.sbiThreshold;
    }
    
    public void setSbiThreshold(SbiThreshold sbiThreshold) {
        this.sbiThreshold = sbiThreshold;
    }

    public SbiDomains getSeverity() {
		return severity;
	}

	public void setSeverity(SbiDomains severity) {
		this.severity = severity;
	}

	public Double getMinValue() {
        return this.minValue;
    }
    
    public void setMinValue(Double minValue) {
        this.minValue = minValue;
    }

    public Double getMaxValue() {
        return this.maxValue;
    }
    
    public void setMaxValue(Double maxValue) {
        this.maxValue = maxValue;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getColour() {
        return this.colour;
    }
    
    public void setColour(String colour) {
        this.colour = colour;
    }

    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
   
    public Set getSbiAlarms() {
        return this.sbiAlarms;
    }
    
    public void setSbiAlarms(Set sbiAlarms) {
        this.sbiAlarms = sbiAlarms;
    }

	public Boolean getMinClosed() {
		return minClosed;
	}

	public void setMinClosed(Boolean minClosed) {
		this.minClosed = minClosed;
	}

	public Boolean getMaxClosed() {
		return maxClosed;
	}

	public void setMaxClosed(Boolean maxClosed) {
		this.maxClosed = maxClosed;
	}

	public Double getThValue() {
		return thValue;
	}

	public void setThValue(Double value) {
		this.thValue = value;
	}

}
