/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.analiticalmodel.functionalitytree.metadata;

import it.eng.spagobi.commons.metadata.SbiHibernateModel;


/**
 * SbiFuncRole generated by hbm2java
 */
public class SbiFuncRole  extends SbiHibernateModel {

    // Fields    

     private SbiFuncRoleId id;
     private String stateCd;


    // Constructors

    /**
     * default constructor.
     */
    public SbiFuncRole() {
    }
    
    /**
     * constructor with id.
     * 
     * @param id the id
     */
    public SbiFuncRole(SbiFuncRoleId id) {
        this.id = id;
    }
   
    
    

    // Property accessors

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public SbiFuncRoleId getId() {
        return this.id;
    }
    
    /**
     * Sets the id.
     * 
     * @param id the new id
     */
    public void setId(SbiFuncRoleId id) {
        this.id = id;
    }

    /**
     * Gets the state cd.
     * 
     * @return the state cd
     */
    public String getStateCd() {
        return this.stateCd;
    }
    
    /**
     * Sets the state cd.
     * 
     * @param stateCd the new state cd
     */
    public void setStateCd(String stateCd) {
        this.stateCd = stateCd;
    }



}