CREATE TABLE SBI_OBJ_PARVIEW (
       OBJ_PAR_ID 			INTEGER NOT NULL,
   	   OBJ_PAR_FATHER_ID    INTEGER NOT NULL,
       OPERATION  			VARCHAR2(20) NOT NULL,
   	   COMPARE_VALUE  		VARCHAR2(200) NOT NULL,
   	   VIEW_LABEL   		VARCHAR2(50),
	   PROG INTEGER,
       USER_IN           	VARCHAR2(100) NOT NULL,
       USER_UP              VARCHAR2(100),
       USER_DE              VARCHAR2(100),
       TIME_IN              TIMESTAMP NOT NULL,
       TIME_UP              TIMESTAMP NULL DEFAULT NULL,
       TIME_DE              TIMESTAMP NULL DEFAULT NULL,
       SBI_VERSION_IN       VARCHAR2(10),
       SBI_VERSION_UP       VARCHAR2(10),
       SBI_VERSION_DE       VARCHAR2(10),
       META_VERSION         VARCHAR2(100),
       ORGANIZATION         VARCHAR2(20),    
  PRIMARY KEY ( OBJ_PAR_ID ,  OBJ_PAR_FATHER_ID ,  OPERATION, COMPARE_VALUE )
);


CREATE INDEX XAK1SBI_PARVIEW ON SBI_OBJ_PARVIEW ( OBJ_PAR_ID ASC, OBJ_PAR_FATHER_ID ASC);
/


ALTER TABLE SBI_OBJ_PARVIEW ADD CONSTRAINT FK_SBI_OBJ_PARVIEW_1 FOREIGN KEY ( OBJ_PAR_ID ) REFERENCES SBI_OBJ_PAR ( OBJ_PAR_ID ) ON DELETE RESTRICT;
ALTER TABLE SBI_OBJ_PARVIEW ADD CONSTRAINT FK_SBI_OBJ_PARVIEW_2 FOREIGN KEY ( OBJ_PAR_FATHER_ID ) REFERENCES SBI_OBJ_PAR ( OBJ_PAR_ID ) ON DELETE RESTRICT;