DROP TABLE TWITTER_SENTIMENT CASCADE CONSTRAINTS;

DROP TABLE TWITTER_SEARCH_SCHEDULER CASCADE CONSTRAINTS;

DROP TABLE TWITTER_MONITOR_SCHEDULER CASCADE CONSTRAINTS;

DROP TABLE TWITTER_LINK_TO_MONITOR_CAT CASCADE CONSTRAINTS;

DROP TABLE TWITTER_LINKS_TO_MONITOR CASCADE CONSTRAINTS;

DROP TABLE TWITTER_ACCOUNTS_TO_MONITOR CASCADE CONSTRAINTS;

DROP TABLE TWITTER_DATA CASCADE CONSTRAINTS;

DROP TABLE TWITTER_USERS CASCADE CONSTRAINTS;

DROP TABLE TWITTER_SEARCH CASCADE CONSTRAINTS;

DROP TABLE TWITTER_HIBERNATE_SEQUENCES CASCADE CONSTRAINTS;