drop sequence SBI_CHECKS_SEQ;                                                   
drop sequence SBI_DOMAINS_SEQ;                                                  
drop sequence SBI_ENGINES_SEQ;                                                  
drop sequence SBI_EXT_ROLES_SEQ;                                                
drop sequence SBI_FUNCTIONS_SEQ;                                                
drop sequence SBI_LOV_SEQ;                                                      
drop sequence SBI_MENU_SEQ;                                                     
drop sequence SBI_OBJECTS_SEQ;                                                  
drop sequence SBI_PARAMETERS_SEQ;                                               
drop sequence SBI_PARUSE_SEQ;                                                   
drop sequence SBI_OBJ_PAR_SEQ;                                                                              
drop sequence SBI_EVENTS_LOG_SEQ;                                               
drop sequence SBI_AUDIT_SEQ;                                                    
drop sequence SBI_ACTIVITY_SEQ;                                                 
drop sequence SBI_VIEWPOINTS_SEQ;                                               
drop sequence SBI_GEO_MAPS_SEQ;                                                 
drop sequence SBI_GEO_FEATURES_SEQ;                                             
drop sequence SBI_DATA_SOURCE_SEQ;                                              
drop sequence SBI_BINARY_CONTENTS_SEQ;                                          
drop sequence SBI_OBJECT_TEMPLATES_SEQ;                                         
drop sequence SBI_OBJECT_NOTES_SEQ;                                             
drop sequence SBI_SUBOBJECTS_SEQ;                                                                        
drop sequence SBI_SNAPSHOTS_SEQ;                                                
drop sequence SBI_USER_FUNC_SEQ;                                                
drop sequence SBI_DOSSIER_PRES_SEQ;                                             
drop sequence SBI_DOSSIER_TEMP_SEQ;                                             
drop sequence SBI_DOSSIER_BIN_TEMP_SEQ;                                         
drop sequence SBI_REMEMBER_ME_SEQ;                                              
drop sequence SBI_DATA_SET_SEQ;                                                 
drop sequence SBI_DIST_LIST_SEQ;                                                
drop sequence SBI_DIST_LIST_USER_SEQ;                                           
drop sequence SBI_DIST_LIST_OBJECTS_SEQ;                                        
drop sequence SBI_UDP_VALUE_SEQ;                                                                                
drop sequence SBI_UDP_SEQ;                                                      
drop sequence SBI_KPI_INSTANCE_HISTORY_SEQ;                                     
drop sequence SBI_KPI_INSTANCE_SEQ;                                             
drop sequence SBI_KPI_MODEL_INST_SEQ;                                           
drop sequence SBI_KPI_MODEL_SEQ;                                                
drop sequence SBI_KPI_VALUE_SEQ;                                                
drop sequence SBI_KPI_SEQ;                                                      
drop sequence SBI_KPI_INST_PERIOD_SEQ;                                          
drop sequence SBI_KPI_MODEL_RESOURCES_SEQ;                                      
drop sequence SBI_KPI_DOCUMENTS_SEQ;                                            
drop sequence RESOURCES_SEQ;                                                                                     
drop sequence SBI_THRESHOLD_SEQ;                                                
drop sequence SBI_THRESHOLD_VAULE_SEQ;                                          
drop sequence SBI_KPI_PERIODICITY_SEQ;                                          
drop sequence SBI_MEASURE_UNIT_SEQ;                                             
drop sequence SBI_OBJ_METADATA_SEQ;                                             
drop sequence SBI_OBJ_METACONTENTS_SEQ;                                         
drop sequence SBI_CONFIG_SEQ;                                                   
drop sequence SBI_KPI_MODEL_ATTR_VAL_SEQ;                                       
drop sequence SBI_KPI_MODEL_ATTR_SEQ; 

drop table SBI_KPI_DOCUMENTS cascade constraints;                               
drop table SBI_UDP cascade constraints;                                         
drop table SBI_UDP_VALUE cascade constraints;                                   
drop table SBI_KPI_REL cascade constraints;                                     
drop table SBI_KPI_ERROR cascade constraints;                                   
drop table SBI_ORG_UNIT cascade constraints;                                    
drop table SBI_ORG_UNIT_HIERARCHIES cascade constraints;                        
drop table SBI_ORG_UNIT_NODES cascade constraints;                              
drop table SBI_ORG_UNIT_GRANT cascade constraints;                              
drop table SBI_ORG_UNIT_GRANT_NODES cascade constraints;                        
drop table SBI_LOV cascade constraints;                                                        
drop table SBI_MENU cascade constraints;                                        
drop table SBI_MENU_ROLE cascade constraints;                                   
drop table SBI_OBJ_FUNC cascade constraints;                                    
drop table SBI_OBJ_PAR cascade constraints;                                     
drop table SBI_OBJ_PARUSE cascade constraints;                                  
drop table SBI_OBJ_STATE cascade constraints;                                   
drop table SBI_OBJECT_NOTES cascade constraints;                                
drop table SBI_OBJECT_TEMPLATES cascade constraints;                            
drop table SBI_OBJECTS cascade constraints;                                     
drop table SBI_OBJECTS_RATING cascade constraints;                              
drop table SBI_PARAMETERS cascade constraints;                                                
drop table SBI_PARUSE cascade constraints;                                      
drop table SBI_PARUSE_CK cascade constraints;                                   
drop table SBI_PARUSE_DET cascade constraints;                                  
drop table SBI_REMEMBER_ME cascade constraints;                                 
drop table SBI_ROLE_TYPE_USER_FUNC cascade constraints;                         
drop table SBI_SNAPSHOTS cascade constraints;                                   
drop table SBI_SUBOBJECTS cascade constraints;                                  
drop table SBI_SUBREPORTS cascade constraints;                                  
drop table SBI_USER_FUNC cascade constraints;                                   
drop table SBI_VIEWPOINTS cascade constraints;                                  
drop table SBI_KPI_ROLE cascade constraints;                                                  
drop table SBI_KPI cascade constraints;                                         
drop table SBI_KPI_VALUE cascade constraints;                                   
drop table SBI_MEASURE_UNIT cascade constraints;                                
drop table SBI_THRESHOLD cascade constraints;                                   
drop table SBI_THRESHOLD_VALUE cascade constraints;                             
drop table SBI_KPI_MODEL cascade constraints;                                   
drop table SBI_KPI_PERIODICITY cascade constraints;                             
drop table SBI_KPI_INSTANCE cascade constraints;                                
drop table SBI_KPI_INSTANCE_HISTORY cascade constraints;                        
drop table SBI_KPI_INST_PERIOD cascade constraints;                             
drop table SBI_KPI_MODEL_INST cascade constraints;                                            
drop table SBI_RESOURCES cascade constraints;                                   
drop table SBI_KPI_MODEL_RESOURCES cascade constraints;                         
drop table SBI_ALARM cascade constraints;                                       
drop table SBI_AUDIT cascade constraints;                                       
drop table SBI_ACTIVITY_MONITORING cascade constraints;                         
drop table SBI_BINARY_CONTENTS cascade constraints;                             
drop table SBI_CHECKS cascade constraints;                                      
drop table SBI_DATA_SET cascade constraints;                                    
drop table SBI_DATA_SOURCE cascade constraints;                                 
drop table SBI_DIST_LIST cascade constraints;                                   
drop table SBI_DIST_LIST_USER cascade constraints;                                              
drop table SBI_DIST_LIST_OBJECTS cascade constraints;                           
drop table SBI_DOMAINS cascade constraints;                                     
drop table SBI_DOSSIER_BIN_TEMP cascade constraints;                            
drop table SBI_DOSSIER_TEMP cascade constraints;                                
drop table SBI_DOSSIER_PRES cascade constraints;                                
drop table SBI_ENGINES cascade constraints;                                     
drop table SBI_EVENTS cascade constraints;                                      
drop table SBI_EVENTS_LOG cascade constraints;                                  
drop table SBI_EVENTS_ROLES cascade constraints;                                
drop table SBI_EXT_ROLES cascade constraints;                                   
drop table SBI_FUNC_ROLE cascade constraints;                                              
drop table SBI_FUNCTIONS cascade constraints;                                   
drop table SBI_GEO_FEATURES cascade constraints;                                
drop table SBI_GEO_MAP_FEATURES cascade constraints;                            
drop table SBI_GEO_MAPS cascade constraints;                                    
drop table SBI_ALARM_EVENT cascade constraints;                                 
drop table SBI_ALARM_DISTRIBUTION cascade constraints;                          
drop table SBI_ALARM_CONTACT cascade constraints;                               
drop table SBI_EXPORTERS cascade constraints;                                   
drop table SBI_OBJ_METADATA cascade constraints;                                
drop table SBI_OBJ_METACONTENTS cascade constraints;                            
drop table SBI_CONFIG cascade constraints;                                                    
drop table SBI_USER cascade constraints;                                        
drop table SBI_ATTRIBUTE cascade constraints;                                   
drop table SBI_USER_ATTRIBUTES cascade constraints;                             
drop table SBI_EXT_USER_ROLES cascade constraints;  
