CREATE TABLE TWITTER_HIBERNATE_SEQUENCES (
  SEQUENCE_NAME VARCHAR2(200) NOT NULL,
  NEXT_VAL INTEGER NOT NULL,
  PRIMARY KEY (SEQUENCE_NAME)
);

CREATE TABLE TWITTER_USERS (
	USER_ID 				INTEGER NOT NULL,
	USERNAME 				VARCHAR2(45) NOT NULL,
	DESCRIPTION 			VARCHAR2(200) DEFAULT NULL,
	FOLLOWERS_COUNT 		INTEGER DEFAULT 0,
	PROFILE_IMAGE_SOURCE 	VARCHAR2(200) NOT NULL,
	LOCATION 				VARCHAR2(200) DEFAULT NULL,
	LOCATION_CODE 			VARCHAR2(45) DEFAULT NULL,
	LANGUAGE_CODE 			VARCHAR2(5) DEFAULT NULL,
	NAME 					VARCHAR2(45) NOT NULL,
	TIME_ZONE 				VARCHAR2(200) DEFAULT NULL,
	TWEETS_COUNT 			INTEGER DEFAULT 0,
	VERIFIED 				SMALLINT DEFAULT 0,
	FOLLOWING_COUNT 		INTEGER DEFAULT 0,
	UTC_OFFSET 				INTEGER DEFAULT NULL,
	IS_GEO_ENABLED 			SMALLINT DEFAULT 0,
	LISTED_COUNT 			INTEGER DEFAULT 0,
	START_DATE 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	END_DATE 				TIMESTAMP DEFAULT NULL,
	PRIMARY KEY (USER_ID),
	CONSTRAINT XAK1TWITTER_USERS UNIQUE (USERNAME)
);


CREATE TABLE TWITTER_SEARCH (
	SEARCH_ID 				INTEGER NOT NULL,
	LABEL 					VARCHAR2(100) NOT NULL,
	KEYWORDS 				VARCHAR2(200) NOT NULL,
	CREATION_DATE 			DATE NOT NULL,
	LAST_ACTIVATION_TIME 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	TYPE					VARCHAR2(50) NOT NULL,
	LOADING 				SMALLINT DEFAULT 1,
	DELETED 				SMALLINT DEFAULT 0,
	FAILED 					SMALLINT DEFAULT 0,
	FAIL_MESSAGE 			VARCHAR2(500) DEFAULT NULL,
	BOOLEAN_OPERATOR 		VARCHAR2(10) DEFAULT 'OR',
	DAYS_AGO 				INTEGER DEFAULT NULL,
	R_ANALYSIS 				SMALLINT DEFAULT 0,
	PRIMARY KEY (SEARCH_ID),
	CONSTRAINT XAK1TWITTER_SEARCH UNIQUE (LABEL)
);


CREATE TABLE TWITTER_DATA (
	TWEET_ID 				INTEGER NOT NULL,
	USER_ID 				INTEGER NOT NULL,
	SEARCH_ID 				INTEGER NOT NULL,
	DATE_CREATED_AT 		DATE NOT NULL,
	TIME_CREATED_AT 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SOURCE_CLIENT 			VARCHAR2(200) NOT NULL,
	TWEET_TEXT 				VARCHAR2(400) NOT NULL,
	TWEET_TEXT_TRANSLATED 	VARCHAR2(400) DEFAULT NULL,
	GEO_LATITUDE 			NUMBER(38,0) DEFAULT NULL,
	GEO_LONGITUDE 			NUMBER(38,0) DEFAULT NULL,
	HASHTAGS 				VARCHAR2(200) DEFAULT NULL,
	MENTIONS 				VARCHAR2(200) DEFAULT NULL,
	RETWEET_COUNT 			INTEGER DEFAULT 0,
	IS_RETWEET 				SMALLINT DEFAULT 0,
	LANGUAGE_CODE 			VARCHAR2(5) DEFAULT NULL,
	PLACE_COUNTRY 			VARCHAR2(200) DEFAULT NULL,
	PLACE_NAME 				VARCHAR2(200) DEFAULT NULL,
	URL_CITED 				VARCHAR2(200) DEFAULT NULL,
	IS_FAVORITED 			SMALLINT DEFAULT 0,
	FAVORITED_COUNT 		INTEGER DEFAULT 0,
	REPLY_TO_SCREEN_NAME 	VARCHAR2(45) DEFAULT NULL,
	REPLY_TO_USER_ID 		VARCHAR2(45) DEFAULT NULL,
	REPLY_TO_TWEET_ID 		VARCHAR2(45) DEFAULT NULL,
	ORIGINAL_RT_TWEET_ID 	VARCHAR2(45) DEFAULT NULL,
	IS_SENSITIVE 			SMALLINT DEFAULT 0,
	MEDIA_COUNT 			INTEGER DEFAULT 0,
	TOPICS 					  VARCHAR2(1000) DEFAULT NULL,
	IS_POSITIVE 			SMALLINT DEFAULT 0,
	IS_NEUTRAL 				SMALLINT DEFAULT 0,
	IS_NEGATIVE 			SMALLINT DEFAULT 0,
	PRIMARY KEY (TWEET_ID, SEARCH_ID)
);


CREATE TABLE TWITTER_SENTIMENT (
	SENTIMENT_ID 			INTEGER NOT NULL,
	TWEET_ID 				INTEGER NOT NULL,
	POLARITY 				VARCHAR2(45) DEFAULT NULL,
	RICH_SENTIMENT 			VARCHAR2(45) DEFAULT NULL,
	TOPICS 					VARCHAR2(45) DEFAULT NULL,
	KLOUT_SCORE 			VARCHAR2(45) DEFAULT NULL,
	PRIMARY KEY (SENTIMENT_ID)
);



CREATE TABLE TWITTER_SEARCH_SCHEDULER (
	ID 						INTEGER NOT NULL,
	SEARCH_ID 				INTEGER NOT NULL,
	STARTING_TIME 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	REPEAT_FREQUENCY 		INTEGER NOT NULL,
	REPEAT_TYPE 			VARCHAR2(45) NOT NULL,
	ACTIVE 					SMALLINT DEFAULT 1,
	PRIMARY KEY (ID)
);



CREATE TABLE TWITTER_MONITOR_SCHEDULER (
	ID 						INTEGER NOT NULL,
	SEARCH_ID 				INTEGER NOT NULL,
	LAST_ACTIVATION_TIME  	TIMESTAMP DEFAULT NULL,
	STARTING_TIME 			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ENDING_TIME 			TIMESTAMP DEFAULT NULL,
	REPEAT_FREQUENCY 		INTEGER NOT NULL,
	REPEAT_TYPE 			VARCHAR2(45) NOT NULL,
	ACTIVE_SEARCH 			SMALLINT DEFAULT 0,
	UP_TO_VALUE 			INTEGER NOT NULL,
	UP_TO_TYPE 				VARCHAR2(50) NOT NULL,
	LINKS 					VARCHAR2(500) DEFAULT NULL,
	ACCOUNTS 				VARCHAR2(500) DEFAULT NULL,
	DOCUMENTS 				VARCHAR2(500) DEFAULT NULL,
	ACTIVE 					SMALLINT DEFAULT 1,
	PRIMARY KEY (ID)
);


CREATE TABLE TWITTER_LINKS_TO_MONITOR (
	ID 						INTEGER NOT NULL,
	SEARCH_ID 				INTEGER NOT NULL,
	LINK 					VARCHAR2(45) NOT NULL,
	LONG_URL 				VARCHAR2(400) DEFAULT NULL,
	CLICKS_COUNT 			INTEGER DEFAULT 0,
	TIMESTAMP 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);


CREATE TABLE TWITTER_LINK_TO_MONITOR_CAT (
	ID 						INTEGER NOT NULL,
	LINK_ID 				INTEGER NOT NULL,
	TYPE 					VARCHAR2(45) NOT NULL,
	CATEGORY 				VARCHAR2(45) NOT NULL,
	CLICKS_COUNT 			INTEGER DEFAULT 0,
	PRIMARY KEY (ID)
);


CREATE TABLE TWITTER_ACCOUNTS_TO_MONITOR (
	ID 						INTEGER NOT NULL,
	SEARCH_ID 				INTEGER NOT NULL,
	ACCOUNT_NAME 			VARCHAR2(45) NOT NULL,
	FOLLOWERS_COUNT 		INTEGER DEFAULT 0,
	TIMESTAMP 				TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);



ALTER TABLE TWITTER_DATA ADD CONSTRAINT FK_TWITTER_DATA_TWITTER_SEARCH FOREIGN KEY (SEARCH_ID) REFERENCES TWITTER_SEARCH (SEARCH_ID);
ALTER TABLE TWITTER_DATA ADD CONSTRAINT FK_TWITTER_DATA_TWITTER_USER FOREIGN KEY (USER_ID) REFERENCES TWITTER_USERS (USER_ID);

--ALTER TABLE TWITTER_SENTIMENT ADD CONSTRAINT FK_TWITTER_SENTIMENT_TWITTER_DATA FOREIGN KEY (TWEET_ID) REFERENCES TWITTER_DATA (TWEET_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE TWITTER_SEARCH_SCHEDULER ADD CONSTRAINT FK_T_SEARCH_SCHEDULER_T_SEARCH FOREIGN KEY (SEARCH_ID) REFERENCES TWITTER_SEARCH (SEARCH_ID);

ALTER TABLE TWITTER_MONITOR_SCHEDULER ADD CONSTRAINT FK_T_MON_SCHEDULER_T_SEARCH FOREIGN KEY (SEARCH_ID) REFERENCES TWITTER_SEARCH (SEARCH_ID);

ALTER TABLE TWITTER_LINKS_TO_MONITOR ADD CONSTRAINT FK_T_LINKS_TO_MONITOR_T_SEARCH FOREIGN KEY (SEARCH_ID) REFERENCES TWITTER_SEARCH (SEARCH_ID);

ALTER TABLE TWITTER_LINK_TO_MONITOR_CAT ADD CONSTRAINT FK_TLINK_MON_CAT_TLINKS_MON FOREIGN KEY (LINK_ID) REFERENCES TWITTER_LINKS_TO_MONITOR (ID);

ALTER TABLE TWITTER_ACCOUNTS_TO_MONITOR ADD CONSTRAINT FK_T_ACC_TO_MONITOR_T_SEARCH FOREIGN KEY (SEARCH_ID) REFERENCES TWITTER_SEARCH (SEARCH_ID);



//TODO NOT NULL e ON UPDATE/DELETE