/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.behaviouralmodel.lov.metadata;

import it.eng.spagobi.commons.metadata.SbiDomains;
import it.eng.spagobi.commons.metadata.SbiHibernateModel;





/**
 * SbiLov generated by hbm2java
 */
public class SbiLov  extends SbiHibernateModel {

    // Fields    

     private Integer lovId;
     private SbiDomains inputType;
     private String inputTypeCd;
     private String defaultVal;
     private String label;
     private String descr;
     private String profileAttr;
     private String lovProvider;
     private String name;


    // Constructors

    /**
     * default constructor.
     */
    public SbiLov() {
    }
    
    /**
     * constructor with id.
     * 
     * @param lovId the lov id
     */
    public SbiLov(Integer lovId) {
        this.lovId = lovId;
    }
   
    
    

    // Property accessors

    /**
     * Gets the lov id.
     * 
     * @return the lov id
     */
    public Integer getLovId() {
        return this.lovId;
    }
    
    /**
     * Sets the lov id.
     * 
     * @param lovId the new lov id
     */
    public void setLovId(Integer lovId) {
        this.lovId = lovId;
    }


    /**
     * Gets the input type cd.
     * 
     * @return the input type cd
     */
    public String getInputTypeCd() {
        return this.inputTypeCd;
    }
    
    /**
     * Sets the input type cd.
     * 
     * @param inputTypeCd the new input type cd
     */
    public void setInputTypeCd(String inputTypeCd) {
        this.inputTypeCd = inputTypeCd;
    }

    /**
     * Gets the default val.
     * 
     * @return the default val
     */
    public String getDefaultVal() {
        return this.defaultVal;
    }
    
    /**
     * Sets the default val.
     * 
     * @param defaultVal the new default val
     */
    public void setDefaultVal(String defaultVal) {
        this.defaultVal = defaultVal;
    }

    /**
     * Gets the label.
     * 
     * @return the label
     */
    public String getLabel() {
        return this.label;
    }
    
    /**
     * Sets the label.
     * 
     * @param label the new label
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * Gets the descr.
     * 
     * @return the descr
     */
    public String getDescr() {
        return this.descr;
    }
    
    /**
     * Sets the descr.
     * 
     * @param descr the new descr
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * Gets the profile attr.
     * 
     * @return the profile attr
     */
    public String getProfileAttr() {
        return this.profileAttr;
    }
    
    /**
     * Sets the profile attr.
     * 
     * @param profileAttr the new profile attr
     */
    public void setProfileAttr(String profileAttr) {
        this.profileAttr = profileAttr;
    }

    /**
     * Gets the lov provider.
     * 
     * @return the lov provider
     */
    public String getLovProvider() {
        return this.lovProvider;
    }
    
    /**
     * Sets the lov provider.
     * 
     * @param lovProvider the new lov provider
     */
    public void setLovProvider(String lovProvider) {
        this.lovProvider = lovProvider;
    }


	/**
	 * Gets the input type.
	 * 
	 * @return the input type
	 */
	public SbiDomains getInputType() {
		return inputType;
	}
	
	/**
	 * Sets the input type.
	 * 
	 * @param inputType the new input type
	 */
	public void setInputType(SbiDomains inputType) {
		this.inputType = inputType;
	}
	
	/**
	 * Gets the name.
	 * 
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * Sets the name.
	 * 
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}
}