package it.eng.spagobi.kpi.ou.metadata;

import it.eng.spagobi.kpi.model.metadata.SbiKpiModelInst;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3



/**
 * SbiOrgUnitGrantNodes generated by hbm2java
 */

public class SbiOrgUnitGrantNodes  implements java.io.Serializable {


    // Fields    

     private SbiOrgUnitGrantNodesId id;
     private SbiOrgUnitNodes sbiOrgUnitNodes;
     private SbiKpiModelInst sbiKpiModelInst;
     private SbiOrgUnitGrant sbiOrgUnitGrant;


    // Constructors

    /** default constructor */
    public SbiOrgUnitGrantNodes() {
    }

    
    /** full constructor */
    public SbiOrgUnitGrantNodes(SbiOrgUnitGrantNodesId id, SbiOrgUnitNodes sbiOrgUnitNodes, SbiKpiModelInst sbiKpiModelInst, SbiOrgUnitGrant sbiOrgUnitGrant) {
        this.id = id;
        this.sbiOrgUnitNodes = sbiOrgUnitNodes;
        this.sbiKpiModelInst = sbiKpiModelInst;
        this.sbiOrgUnitGrant = sbiOrgUnitGrant;
    }
    

   
    // Property accessors

    public SbiOrgUnitGrantNodesId getId() {
        return this.id;
    }
    
    public void setId(SbiOrgUnitGrantNodesId id) {
        this.id = id;
    }

    public SbiOrgUnitNodes getSbiOrgUnitNodes() {
        return this.sbiOrgUnitNodes;
    }
    
    public void setSbiOrgUnitNodes(SbiOrgUnitNodes sbiOrgUnitNodes) {
        this.sbiOrgUnitNodes = sbiOrgUnitNodes;
    }

    public SbiKpiModelInst getSbiKpiModelInst() {
        return this.sbiKpiModelInst;
    }
    
    public void setSbiKpiModelInst(SbiKpiModelInst sbiKpiModelInst) {
        this.sbiKpiModelInst = sbiKpiModelInst;
    }

    public SbiOrgUnitGrant getSbiOrgUnitGrant() {
        return this.sbiOrgUnitGrant;
    }
    
    public void setSbiOrgUnitGrant(SbiOrgUnitGrant sbiOrgUnitGrant) {
        this.sbiOrgUnitGrant = sbiOrgUnitGrant;
    }
   








}
