/*
 * SpagoBI, the Open Source Business Intelligence suite
 * © 2005-2015 Engineering Group
 *
 * This file is part of SpagoBI. SpagoBI is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or any later version. 
 * SpagoBI is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received
 * a copy of the GNU Lesser General Public License along with SpagoBI. If not, see: http://www.gnu.org/licenses/.
 * The complete text of SpagoBI license is included in the COPYING.LESSER file. 
 */
package it.eng.spagobi.kpi.ou.metadata;
// Generated 21-set-2010 12.29.29 by Hibernate Tools 3.1.0 beta3

import it.eng.spagobi.commons.metadata.SbiHibernateModel;

import java.util.HashSet;
import java.util.Set;


/**
 * SbiOrgUnit generated by hbm2java
 */

public class SbiOrgUnit  extends SbiHibernateModel {


    // Fields    

     private Integer id;
     private String label;
     private String name;
     private String description;
     private Set sbiOrgUnitNodeses = new HashSet(0);


    // Constructors

    /** default constructor */
    public SbiOrgUnit() {
    }

	/** minimal constructor */
    public SbiOrgUnit(Integer id, String label, String name) {
        this.id = id;
        this.label = label;
        this.name = name;
    }
    
    /** full constructor */
    public SbiOrgUnit(Integer id, String label, String name, String description, Set sbiOrgUnitNodeses) {
        this.id = id;
        this.label = label;
        this.name = name;
        this.description = description;
        this.sbiOrgUnitNodeses = sbiOrgUnitNodeses;
    }
    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getSbiOrgUnitNodeses() {
        return this.sbiOrgUnitNodeses;
    }
    
    public void setSbiOrgUnitNodeses(Set sbiOrgUnitNodeses) {
        this.sbiOrgUnitNodeses = sbiOrgUnitNodeses;
    }
   








}
