EXEC sp_rename 'SBI_OBJ_METADATA.DESCRIPTION', 'DESCR', 'COLUMN';
--if previous stmt doesn't work try with nexts:
--ALTER TABLE SBI_OBJ_METADATA ADD COLUMN DESCR VARCHAR(100) NULL;
--UPDATE SBI_OBJ_METADATA SET DESCR = DESCRIPTION;
--COMMIT;
--ALTER TABLE SBI_OBJ_METADATA DROP COLUMN DESCRIPTION;